# Generated by Django 3.2.14 on 2023-08-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_package", "0004_alter_orderpackage_weight_unit"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="order",
        ),
        migrations.AddField(
            model_name="shipment",
            name="package",
            field=models.ForeignKey(
                null=True,
                related_name="shipment_packages",
                on_delete=django.db.models.deletion.SET_NULL,
                to="order_package.orderpackage",
            ),
        ),
    ]
