# Generated by Django 3.2.14 on 2023-08-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_service_types", "0001_initial"),
        ("shipments", "0002_auto_20230804_0924"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping_service_types.shippingservicetype",
            ),
        ),
    ]
