# Generated by Django 3.2.14 on 2023-08-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_package", "0004_alter_orderpackage_weight_unit"),
        ("shipments", "0003_shipment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="package",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment_packages",
                to="order_package.orderpackage",
            ),
        ),
    ]
