# Generated by Django 3.2.14 on 2023-08-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0005_alter_shipment_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="identification_number",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="shipment",
            name="sender_country",
            field=models.CharField(default="US", max_length=128),
        ),
    ]
