# Generated by Django 3.2.14 on 2023-08-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0005_alter_shipment_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="sscc",
            field=models.CharField(default="", max_length=100),
        ),
    ]
