# Generated by Django 3.2.14 on 2023-08-12 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0006_auto_20230812_0418"),
        ("shipments", "0006_shipment_sscc"),
    ]

    operations = []
