# Generated by Django 3.2.14 on 2023-08-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0007_merge_0006_auto_20230812_0418_0006_shipment_sscc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="sscc",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
