# Generated by Django 3.2.14 on 2023-08-22 06:54

from django.db import migrations


def update_sscc_data(apps, schema_editor):
    Shipment = apps.get_model("shipments", "Shipment")
    shipment_list = Shipment.objects.filter(sscc__isnull=False)
    for shipment_item in shipment_list:
        current_sscc = shipment_item.sscc
        if len(current_sscc) == 18:
            shipment_item.sscc = "00" + current_sscc
            shipment_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0008_alter_shipment_sscc"),
    ]

    operations = [
        migrations.RunPython(update_sscc_data),
    ]
