# Generated by Django 3.2.14 on 2023-11-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0009_update_sscc_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="ship_times",
            field=models.IntegerField(default=1),
        ),
    ]
