# Generated by Django 3.2.14 on 2023-11-28 07:15

from django.db import migrations, models

from selleraxis.shipments.models import ShipmentStatus


def recheck_status(apps, schema_editor):
    # get all shipment
    Shipment = apps.get_model("shipments", "Shipment")
    list_shipment = Shipment.objects.all()
    for shipment_item in list_shipment:
        if shipment_item.status.upper() == "CANCELED":
            shipment_item.status = ShipmentStatus.VOIDED
            shipment_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0010_shipment_ship_times"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("VOIDED", "Voided"),
                    ("SUBMITTED", "Submitted"),
                ],
                max_length=128,
            ),
        ),
        migrations.RunPython(recheck_status),
    ]
