# Generated by Django 3.2.14 on 2023-11-28 07:15

from django.db import migrations, models

from selleraxis.retailer_purchase_orders.models import QueueStatus
from selleraxis.shipments.models import ShipmentStatus


def recheck_status(apps, schema_editor):
    # get all order
    RetailerPurchaseOrder = apps.get_model(
        "retailer_purchase_orders", "RetailerPurchaseOrder"
    )
    list_order = RetailerPurchaseOrder.objects.all()

    # get all order package
    OrderPackage = apps.get_model("order_package", "OrderPackage")
    list_order_package = OrderPackage.objects.all()

    # get all order history
    RetailerPurchaseOrderHistory = apps.get_model(
        "retailer_purchase_order_histories", "RetailerPurchaseOrderHistory"
    )
    list_order_history = RetailerPurchaseOrderHistory.objects.all()

    # get all shipment
    Shipment = apps.get_model("shipments", "Shipment")
    list_shipment = Shipment.objects.all()
    list_package_id_shipped = []
    for shipment_item in list_shipment:
        if shipment_item.package is not None:
            list_package_id_shipped.append(shipment_item.package.id)

    for order in list_order:
        is_partly_ship = False
        check_full_shipped = True

        # get list package shipped of order
        list_package_for_order = list_order_package.filter(order__id=order.id)
        list_shipment_for_order = list_shipment.filter(
            package__id__in=[package.id for package in list_package_for_order]
        )
        # get list order history of order
        list_order_history_for_order = list_order_history.filter(
            order__id=order.id
        ).order_by("-created_at")

        # if order cancelled
        if order.status.upper() == QueueStatus.Shipment_Confirmed.value.upper():
            Shipment.objects.filter(
                id__in=[shipment.id for shipment in list_shipment_for_order],
                status=ShipmentStatus.CREATED,
            ).update(status=ShipmentStatus.SUBMITTED)
        elif order.status.upper() == QueueStatus.Partly_Shipped_Confirmed.value.upper():
            partly_confirm_latest = None
            for order_history in list_order_history_for_order:
                if (
                    order_history.status.upper()
                    == QueueStatus.Partly_Shipped_Confirmed.value.upper()
                ):
                    partly_confirm_latest = order_history
                    break
            if partly_confirm_latest is not None:
                Shipment.objects.filter(
                    id__in=[shipment.id for shipment in list_shipment_for_order],
                    create_at__lte=partly_confirm_latest.create_at,
                    status=ShipmentStatus.CREATED,
                ).update(status=ShipmentStatus.SUBMITTED)


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0011_alter_shipment_status_canceled_to_voided"),
    ]

    operations = [
        migrations.RunPython(recheck_status),
    ]
