# Generated by Django 3.2.14 on 2023-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_rules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagerule",
            name="dimension_unit",
            field=models.CharField(default="lb", max_length=255),
        ),
        migrations.AddField(
            model_name="packagerule",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="packagerule",
            name="length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="packagerule",
            name="wight",
            field=models.IntegerField(default=0),
        ),
    ]
