# Generated by Django 3.2.14 on 2023-07-14 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("package_rules", "0002_auto_20230711_0714"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagerule",
            name="dimension_unit",
        ),
        migrations.RemoveField(
            model_name="packagerule",
            name="height",
        ),
        migrations.RemoveField(
            model_name="packagerule",
            name="length",
        ),
        migrations.RemoveField(
            model_name="packagerule",
            name="wight",
        ),
    ]
