# Generated by Django 3.2.14 on 2023-07-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("boxes", "0002_remove_box_package_rule"),
        ("products", "0003_remove_product_package_rule"),
        ("package_rules", "0003_auto_20230714_0835"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagerule",
            name="name",
        ),
        migrations.RemoveField(
            model_name="packagerule",
            name="organization",
        ),
        migrations.AddField(
            model_name="packagerule",
            name="box",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="boxes.box"
            ),
        ),
        migrations.AddField(
            model_name="packagerule",
            name="max_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="packagerule",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
    ]
