# Generated by Django 3.2.14 on 2023-07-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_series", "0001_initial"),
        ("package_rules", "0004_auto_20230719_0930"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagerule",
            name="product_series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_series.productseries",
            ),
        ),
    ]
