# Generated by Django 3.2.14 on 2023-07-21 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("package_rules", "0005_packagerule_product_series"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagerule",
            name="product",
        ),
    ]
