# Generated by Django 3.2.14 on 2023-07-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_series", "0001_initial"),
        ("package_rules", "0006_remove_packagerule_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagerule",
            name="product_series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_rules",
                to="product_series.productseries",
            ),
        ),
    ]
