# Generated by Django 3.2.14 on 2023-09-05 06:46

from django.db import migrations


def change_name_error(apps, schema_editor):
    ShippingServiceType = apps.get_model(
        "shipping_service_types", "ShippingServiceType"
    )
    ShippingServiceType.objects.filter(code="PRIORITY_OVERNIGHT").update(
        name="FedEx Priority Overnight"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_service_types", "0001_initial"),
    ]

    operations = [migrations.RunPython(change_name_error)]
