# Generated by Django 3.2.14 on 2023-09-18 09:21

from django.db import migrations, models
from selleraxis.shipping_service_types.models import ShippingServiceType


def set_fedex_home_delivery(apps, schema_editor):
    shipping_service_type = ShippingServiceType.objects.filter(
        code="GROUND_HOME_DELIVERY"
    ).first()
    shipping_service_type.is_require_residential = True
    shipping_service_type.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_service_types", "0002_auto_20230905_0246"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingservicetype",
            name="is_require_residential",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_fedex_home_delivery),
    ]
