# Generated by Django 3.2.14 on 2023-10-20 07:10

from django.db import migrations, models


def migration_add_data_service(apps, schema_editor):
    data = [
        {
            "code": "FEDEX_INTERNATIONAL_PRIORITY_EXPRESS",
            "max_length": 200,
            "max_length_plus_girth": 150,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FIRST_OVERNIGHT",
            "max_length": 200,
            "max_length_plus_girth": 150,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "STANDARD_OVERNIGHT",
            "max_length": 200,
            "max_length_plus_girth": 150,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_2_DAY_AM",
            "max_length": 200,
            "max_length_plus_girth": 150,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_2_DAY",
            "max_length": 200,
            "max_length_plus_girth": 150,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_EXPRESS_SAVER",
            "max_length": 200,
            "max_length_plus_girth": 150,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_GROUND",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "GROUND_HOME_DELIVERY",
            "max_length": 108,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "SMART_POST",
            "max_length": 108,
            "max_length_plus_girth": 84,
            "max_weight": 60,
            "min_weight": 1,
        },
        {
            "code": "INTERNATIONAL_FIRST",
            "max_length": 200,
            "max_length_plus_girth": 84,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_INTERNATIONAL_PRIORITY",
            "max_length": 200,
            "max_length_plus_girth": 84,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "INTERNATIONAL_ECONOMY",
            "max_length": 200,
            "max_length_plus_girth": 84,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_CARGO_MAIL",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_CARGO_INTERNATIONAL_PREMIUM",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FIRST_OVERNIGHT_FREIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_1_DAY_FREIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_2_DAY_FREIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_2_DAY_FREIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_3_DAY_FREIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "INTERNATIONAL_PRIORITY_FREIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "INTERNATIONAL_ECONOMY_FREIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_CARGO_AIRPORT_TO_AIRPORT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "INTERNATIONAL_PRIORITY_DISTRIBUTION",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "FEDEX_IP_DIRECT_DISTRIBUTION_FREIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "INTL_GROUND_DISTRIBUTION",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "SAME_DAY",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "SAME_DAY_CITY",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "PRIORITY_OVERNIGHT",
            "max_length": 200,
            "max_length_plus_girth": 165,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "54",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 55,
            "min_weight": 1,
        },
        {
            "code": "07",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 55,
            "min_weight": 1,
        },
        {
            "code": "96",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 70,
            "min_weight": 1,
        },
        {
            "code": "01",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "02",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "03",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "08",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "08",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "11",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "12",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "13",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "14",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "17",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "65",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "M2",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "M3",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "M4",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "M5",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "M6",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "M7",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "70",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "71",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "72",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "74",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "75",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "82",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "83",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "84",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "85",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "86",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
        {
            "code": "59",
            "max_length": 274,
            "max_length_plus_girth": 400,
            "max_weight": 150,
            "min_weight": 1,
        },
    ]
    ShippingServiceType = apps.get_model(
        "shipping_service_types", "ShippingServiceType"
    )
    shipping_service_types = ShippingServiceType.objects.all()
    update_object_list = []

    for shipping_service_type in shipping_service_types:
        for item in data:
            if shipping_service_type.code == item["code"]:
                shipping_service_type.max_length = item["max_length"]
                shipping_service_type.max_length_plus_girth = item[
                    "max_length_plus_girth"
                ]
                shipping_service_type.max_weight = item["max_weight"]
                shipping_service_type.min_weight = item["min_weight"]
                update_object_list.append(shipping_service_type)

    ShippingServiceType.objects.bulk_update(
        update_object_list,
        ["max_length", "max_length_plus_girth", "max_weight", "min_weight"],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_service_types", "0004_shippingservicetype_commercehub_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingservicetype",
            name="max_length",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="shippingservicetype",
            name="max_length_plus_girth",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="shippingservicetype",
            name="max_weight",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="shippingservicetype",
            name="min_weight",
            field=models.FloatField(null=True),
        ),
        migrations.RunPython(migration_add_data_service),
    ]
