# Generated by Django 3.2.14 on 2023-10-24 07:57

from django.db import migrations, models
from selleraxis.shipping_service_types.models import ShippingServiceType
from selleraxis.services.models import Services


def migration_max_package_data(apps, schema_editor):
    try:
        service = Services.objects.get(name="UPS")
        ShippingServiceType.objects.filter(service=service).update(max_package=100)
    except Services.DoesNotExist:
        # Handle the case where the "UPS" service is not found
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_service_types", "0005_auto_20231020_0310"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingservicetype",
            name="max_package",
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(migration_max_package_data),
    ]
