# Generated by Django 3.2.14 on 2023-10-31 04:58

from django.db import migrations


def migration_max_package_data(apps, schema_editor):
    Services = apps.get_model("services", "Services")
    ShippingServiceType = apps.get_model(
        "shipping_service_types", "ShippingServiceType"
    )
    try:
        # update data service UPS
        service_ups = Services.objects.get(name="UPS")
        ShippingServiceType.objects.filter(service=service_ups).update(max_package=None)
        # update data service Fedex
        service_ups = Services.objects.get(name="FEDEX")
        ShippingServiceType.objects.filter(service=service_ups).update(max_package=108)
    except Services.DoesNotExist:
        # Handle the case where the "UPS" service is not found
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_service_types", "0006_shippingservicetype_max_package"),
    ]

    operations = []
