# Generated by Django 3.2.14 on 2023-07-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="type",
            field=models.CharField(
                choices=[("INVOICE", "Invoice"), ("SHIPPING", "Shipping")],
                max_length=128,
            ),
        ),
    ]
