# Generated by Django 3.2.14 on 2023-08-08 08:51

from django.db import migrations, models
from selleraxis.services.models import Services


def migrate_services(apps, schema_editor):
    Services.objects.filter(name="UPS").update(
        shipment_tracking_url="https://www.ups.com/track?loc=en_VN&requester=ST/"
    )
    Services.objects.filter(name="FEDEX").update(
        shipment_tracking_url="https://www.fedex.com/fedextrack/?trknbr=<tracking_number>"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_services_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="shipment_tracking_url",
            field=models.TextField(null=True),
        ),
        migrations.RunPython(migrate_services),
    ]
