# Generated by Django 3.2.14 on 2023-12-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_services_shipment_tracking_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
