# Generated by Django 3.2.14 on 2023-07-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_warehouse_products", "0001_initial"),
        ("product_warehouse_static_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productwarehousestaticdata",
            name="product_warehouse_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="retailer_warehouse_products.retailerwarehouseproduct",
            ),
        ),
    ]
