# Generated by Django 3.2.14 on 2023-07-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_warehouse_products", "0001_initial"),
        (
            "product_warehouse_static_data",
            "0002_alter_productwarehousestaticdata_product_warehouse_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productwarehousestaticdata",
            name="product_warehouse_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_warehouse_statices",
                to="retailer_warehouse_products.retailerwarehouseproduct",
            ),
        ),
    ]
