# Generated by Django 3.2.14 on 2023-07-13 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_warehouse_static_data",
            "0002_rename_next_available_quty_productwarehousestaticdata_next_available_qty",
        ),
        (
            "product_warehouse_static_data",
            "0003_alter_productwarehousestaticdata_product_warehouse_id",
        ),
    ]

    operations = []
