# Generated by Django 3.2.14 on 2023-07-13 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_warehouse_static_data",
            "0005_alter_productwarehousestaticdata_product_warehouse_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productwarehousestaticdata",
            name="next_available_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="productwarehousestaticdata",
            name="next_available_qty",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
