# Generated by Django 3.2.14 on 2023-07-17 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "retailer_warehouse_products",
            "0003_alter_retailerwarehouseproduct_product_alias",
        ),
        ("product_warehouse_static_data", "0006_auto_20230713_1751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productwarehousestaticdata",
            name="next_available_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="productwarehousestaticdata",
            name="next_available_qty",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="productwarehousestaticdata",
            name="product_warehouse_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="retailer_warehouse_products.retailerwarehouseproduct",
            ),
        ),
    ]
