# Generated by Django 3.2.14 on 2023-07-17 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_warehouse_static_data", "0007_auto_20230717_0222"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productwarehousestaticdata",
            old_name="product_warehouse_id",
            new_name="product_warehouse",
        ),
    ]
