# Generated by Django 3.2.14 on 2023-07-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "retailer_warehouse_products",
            "0003_alter_retailerwarehouseproduct_product_alias",
        ),
        (
            "product_warehouse_static_data",
            "0008_rename_product_warehouse_id_productwarehousestaticdata_retailer_warehouse_product",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productwarehousestaticdata",
            name="product_warehouse",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_warehouse_statices",
                to="retailer_warehouse_products.retailerwarehouseproduct",
            ),
        ),
    ]
