FROM python:3.10
ENV PYTHONUNBUFFERED 1

ARG ENV
ARG SECRET_KEY
ARG DB_NAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_HOST
ARG CORS_ALLOWED_ORIGINS
ARG HOST
ARG BUCKET_NAME
ARG SENDER_EMAIL
ARG UPDATE_INVENTORY_SQS_NAME
ARG UPDATE_RETAILER_INVENTORY_SQS_NAME
ARG UPDATE_INVENTORY_TO_COMMERCEHUB_SQS_NAME
ARG QBO_SYNC_UNHANDLED_DATA_NAME
ARG WEBSITE_URL
ARG DEFAULT_FEDEX_CLIENT_ID
ARG DEFAULT_FEDEX_CLIENT_SECRET
ARG QBO_CLIENT_ID
ARG QBO_CLIENT_SECRET
ARG QBO_ENVIRONMENT
ARG QBO_QUICKBOOK_URL
ARG QBO_REDIRECT_URL
ARG QBO_TOKEN_ENDPOINT

# Allows docker to cache installed dependencies between builds
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Adds our application code to the image
COPY . code
WORKDIR code

EXPOSE 80

ENV DJANGO_SETTINGS_MODULE "selleraxis.settings.production"

ENV ENV ${ENV}
ENV SECRET_KEY ${SECRET_KEY}
ENV DB_NAME ${DB_NAME}
ENV DB_USERNAME ${DB_USERNAME}
ENV DB_PASSWORD ${DB_PASSWORD}
ENV DB_HOST ${DB_HOST}
ENV CORS_ALLOWED_ORIGINS ${CORS_ALLOWED_ORIGINS}
ENV HOST ${HOST}
ENV BUCKET_NAME ${BUCKET_NAME}
ENV SENDER_EMAIL ${SENDER_EMAIL}
ENV UPDATE_INVENTORY_SQS_NAME ${UPDATE_INVENTORY_SQS_NAME}
ENV UPDATE_RETAILER_INVENTORY_SQS_NAME ${UPDATE_RETAILER_INVENTORY_SQS_NAME}
ENV UPDATE_INVENTORY_TO_COMMERCEHUB_SQS_NAME ${UPDATE_INVENTORY_TO_COMMERCEHUB_SQS_NAME}
ENV QBO_SYNC_UNHANDLED_DATA_NAME ${QBO_SYNC_UNHANDLED_DATA_NAME}
ENV WEBSITE_URL ${WEBSITE_URL}
ENV DEFAULT_FEDEX_CLIENT_ID ${DEFAULT_FEDEX_CLIENT_ID}
ENV DEFAULT_FEDEX_CLIENT_SECRET ${DEFAULT_FEDEX_CLIENT_SECRET}
ENV QBO_CLIENT_ID ${QBO_CLIENT_ID}
ENV QBO_CLIENT_SECRET ${QBO_CLIENT_SECRET}
ENV QBO_ENVIRONMENT ${QBO_ENVIRONMENT}
ENV QBO_QUICKBOOK_URL ${QBO_QUICKBOOK_URL}
ENV QBO_REDIRECT_URL ${QBO_REDIRECT_URL}
ENV QBO_TOKEN_ENDPOINT ${QBO_TOKEN_ENDPOINT}

RUN ["chmod", "+x", "./docker-entrypoint.sh"]

# Run the production server
ENTRYPOINT ["./docker-entrypoint.sh"]
