# Generated by Django 3.2.14 on 2023-11-27 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0012_organization_add_live_qbo_token_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="GettingOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="getting_order_history",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
