# Generated by Django 3.2.14 on 2023-09-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_ref_type", "0001_initial"),
        ("shipping_ref", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingref",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_ref_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
    ]
