# Generated by Django 3.2.14 on 2023-10-04 07:10

from django.db import migrations
from selleraxis.shipping_ref.models import ShippingRef


def migration_update_name(apps, shema_editor):
    ShippingRef.objects.filter(name="P O NUMBER").update(name="PO NUMBER")


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_ref", "0002_shippingref_type"),
    ]

    operations = [migrations.RunPython(migration_update_name)]
