# Generated by Django 3.2.14 on 2023-08-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_carriers", "0002_retailercarrier_account_number"),
        ("retailer_shippers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailershipper",
            name="retailer_carrier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipper",
                to="retailer_carriers.retailercarrier",
            ),
        ),
    ]
