# Generated by Django 3.2.14 on 2023-09-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_shippers", "0002_alter_retailershipper_retailer_carrier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailershipper",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="retailershipper",
            name="fax_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="retailershipper",
            name="tax_identification_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
