# Generated by Django 3.2.14 on 2023-07-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_order_batchs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerorderbatch",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="retailerorderbatch",
            name="retailer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retailer_order_batch",
                to="retailers.retailer",
            ),
        ),
    ]
