# Generated by Django 3.2.14 on 2023-11-27 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("getting_order_histories", "0001_initial"),
        ("retailer_order_batchs", "0002_retailerorderbatch_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerorderbatch",
            name="getting_order_history",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="getting_order_history",
                to="getting_order_histories.gettingorderhistory",
            ),
        ),
    ]
