# Generated by Django 3.2.14 on 2023-10-03 04:49

from django.db import migrations

from selleraxis.services.models import Services
from selleraxis.shipping_ref_type.models import ShippingRefType
from selleraxis.shipping_ref.models import ShippingRef


def migration_import_data(apps, schema_editor):
    ShippingRefType.objects.all().delete()
    ShippingRef.objects.all().delete()
    data = {
        "DEPARTMENT NUMBER": None,
        "CUSTOMER REFERENCE": None,
        "INVOICE NUMBER": "{{order.invoice_order.doc_number}}",
        "P O NUMBER": "{{order.po_number}}",
        "REFERENCE": None,
    }
    type_list = []
    for key, value in data.items():
        type_list.append(
            ShippingRefType(
                name=key,
                data_field=value,
            )
        )
    shipping_ref_type = ShippingRefType.objects.bulk_create(type_list)
    service_list = Services.objects.filter(name__in=["UPS", "FEDEX"])
    shipping_ref_list = []
    for service_item in service_list:
        for shipping_ref_type_item in shipping_ref_type:
            name = shipping_ref_type_item.name
            shipping_ref_list.append(
                ShippingRef(
                    name=name,
                    code=name.replace(" ", "_"),
                    service=service_item,
                    type=shipping_ref_type_item,
                )
            )
    ShippingRef.objects.bulk_create(shipping_ref_list)


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_ref_type", "0001_initial"),
    ]

    operations = [migrations.RunPython(migration_import_data)]
