# Generated by Django 3.2.14 on 2023-10-03 07:38

from django.db import migrations
from selleraxis.shipping_ref_type.models import ShippingRefType


def migration_update_name(apps, schema_editor):
    ShippingRefType.objects.filter(name="P O NUMBER").update(name="PO NUMBER")


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_ref_type", "0002_auto_20231003_0049"),
    ]

    operations = [migrations.RunPython(migration_update_name)]
