# Generated by Django 3.2.14 on 2023-10-10 04:01

from django.db import migrations
from selleraxis.shipping_ref_type.models import ShippingRefType
from selleraxis.shipping_ref.models import ShippingRef


def migration_delete_reference_type(apps, schema_editor):
    shipping_ref_type = ShippingRefType.objects.filter(name="REFERENCE").first()
    ShippingRef.objects.filter(type=shipping_ref_type).delete()
    shipping_ref_type.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_ref_type", "0003_auto_20231003_0338"),
    ]

    operations = [migrations.RunPython(migration_delete_reference_type)]
