# Generated by Django 3.2.14 on 2023-07-07 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("retailers", "0002_auto_20230706_0832"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerCommercehubSFTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sftp_host", models.CharField(max_length=225)),
                ("sftp_username", models.CharField(max_length=225)),
                ("sftp_password", models.CharField(max_length=128)),
                (
                    "purchase_orders_sftp_directory",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                (
                    "acknowledgment_sftp_directory",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                (
                    "confirm_sftp_directory",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                (
                    "inventory_sftp_directory",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                (
                    "invoice_sftp_directory",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                (
                    "return_sftp_directory",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                (
                    "payment_sftp_directory",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retailers.retailer",
                    ),
                ),
            ],
        ),
    ]
