# Generated by Django 3.2.14 on 2023-07-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_commercehub_sftp", "0003_auto_20230718_0141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailercommercehubsftp",
            name="confirm_xml_format",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="retailercommercehubsftp",
            name="inventory_xml_format",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="retailercommercehubsftp",
            name="invoice_xml_format",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="retailercommercehubsftp",
            name="payment_xml_format",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="retailercommercehubsftp",
            name="return_xml_format",
            field=models.TextField(blank=True, default=""),
        ),
    ]
