# Generated by Django 3.2.14 on 2023-07-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0002_auto_20230706_0832"),
        ("retailer_commercehub_sftp", "0004_auto_20230720_0439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailercommercehubsftp",
            name="retailer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retailer_commercehub_sftp",
                to="retailers.retailer",
            ),
        ),
    ]
