# Generated by Django 3.2.14 on 2023-08-31 04:49

from django.db import migrations, models
from selleraxis.retailer_commercehub_sftp.models import RetailerCommercehubSFTP

DEFAULT_CONFIRMATION_XSD_FILE_URL = (
    "./selleraxis/retailer_purchase_orders/services/HubXML_Confirmation.xsd"
)


def safe_load_xml_file(file_path):
    try:
        with open(file_path, mode="r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        pass


def forwards(app, app_schema):
    RetailerCommercehubSFTP.objects.update(
        confirm_xml_format=safe_load_xml_file(DEFAULT_CONFIRMATION_XSD_FILE_URL)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_commercehub_sftp", "0008_auto_20230828_0038"),
    ]

    operations = [migrations.RunPython(forwards)]
