# Generated by Django 3.2.14 on 2023-08-08 04:05

from django.db import migrations, models

from selleraxis.retailer_purchase_orders.models import RetailerPurchaseOrder


def migrate_verified_ship_to(apps, schema_editor):
    RetailerPurchaseOrder.objects.all().update(verified_ship_to=None)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("retailer_purchase_orders", "0006_auto_20230802_1115"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderVerifiedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_name", models.CharField(max_length=255)),
                ("address_1", models.CharField(max_length=255)),
                ("address_2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(migrate_verified_ship_to),
    ]
