# Generated by Django 3.2.14 on 2023-08-08 04:05

from django.db import migrations, models

from selleraxis.retailer_purchase_orders.models import RetailerPurchaseOrder
from selleraxis.order_verified_address.models import OrderVerifiedAddress


def migrate_verified_ship_to(apps, schema_editor):
    purchase_orders = RetailerPurchaseOrder.objects.select_related(
        "verified_ship_to"
    ).filter(verified_ship_to__isnull=False)
    verified_addresses = []
    for purchase_order in purchase_orders:
        verified_addresses.append(
            OrderVerifiedAddress(
                pk=purchase_order.verified_ship_to.pk,
                company=purchase_order.verified_ship_to.company,
                contact_name=purchase_order.verified_ship_to.name,
                address_1=purchase_order.verified_ship_to.address_1,
                address_2=purchase_order.verified_ship_to.address_2,
                city=purchase_order.verified_ship_to.city,
                state=purchase_order.verified_ship_to.state,
                postal_code=purchase_order.verified_ship_to.postal_code,
                country=purchase_order.verified_ship_to.country,
                phone=purchase_order.verified_ship_to.day_phone,
                created_at=purchase_order.verified_ship_to.created_at,
                updated_at=purchase_order.verified_ship_to.updated_at,
            )
        )

    OrderVerifiedAddress.objects.bulk_create(verified_addresses, batch_size=1000)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderVerifiedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_name", models.CharField(max_length=255)),
                ("address_1", models.CharField(max_length=255)),
                ("address_2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(migrate_verified_ship_to),
    ]
