# Generated by Django 3.2.14 on 2023-08-11 09:34

from django.db import migrations, models
from selleraxis.retailer_purchase_orders.models import RetailerPurchaseOrder


def forwards(apps, schema_editor):
    OrderVerifiedAddress = apps.get_model(
        "order_verified_address", "OrderVerifiedAddress"
    )
    purchase_orders = RetailerPurchaseOrder.objects.filter(
        verified_ship_to__isnull=False
    )
    OrderVerifiedAddress.objects.filter(
        pk__in=RetailerPurchaseOrder.objects.filter(ship_to__isnull=False).values_list(
            "ship_to__id", flat=True
        )
    ).update(status=OrderVerifiedAddress.Status.VERIFIED.value)


class Migration(migrations.Migration):
    dependencies = [
        ("order_verified_address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderverifiedaddress",
            name="status",
            field=models.CharField(
                choices=[
                    ("EDITED", "EDITED"),
                    ("ORIGIN", "ORIGIN"),
                    ("VERIFIED", "VERIFIED"),
                ],
                default="ORIGIN",
                max_length=255,
            ),
        ),
        migrations.RunPython(forwards),
    ]
