# Generated by Django 3.2.14 on 2023-09-18 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order_verified_address", "0004_alter_orderverifiedaddress_status"),
    ]
    operations = [
        migrations.DeleteModel(
            name="OrderVerifiedAddress",
        ),
    ]
