# Generated by Django 3.2.14 on 2023-12-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_purchase_order_returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerpurchaseorderreturn',
            name='dispute_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailerpurchaseorderreturn',
            name='is_dispute',
            field=models.BooleanField(default=False),
        ),
    ]
