# Generated by Django 3.2.14 on 2023-12-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_purchase_order_returns", "0003_auto_20231227_0152"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorderreturn",
            name="dispute_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
