# Generated by Django 3.2.14 on 2023-07-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_warehouses", "0002_alter_retailerwarehouse_retailer"),
        ("retailer_warehouse_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerwarehouseproduct",
            name="retailer_warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retailer_warehouse_products",
                to="retailer_warehouses.retailerwarehouse",
            ),
        ),
    ]
