# Generated by Django 3.2.14 on 2023-07-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_alias", "0002_auto_20230713_0218"),
        (
            "retailer_warehouse_products",
            "0002_alter_retailerwarehouseproduct_retailer_warehouse",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerwarehouseproduct",
            name="product_alias",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retailer_warehouse_products",
                to="product_alias.productalias",
            ),
        ),
    ]
