# Generated by Django 3.2.14 on 2023-11-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_alias", "0005_productalias_upc"),
        (
            "retailer_warehouse_products",
            "0003_alter_retailerwarehouseproduct_product_alias",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerwarehouseproduct",
            name="product_alias",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retailer_product_aliases",
                to="product_alias.productalias",
            ),
        ),
    ]
