# Generated by Django 3.2.14 on 2023-03-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("retailers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerPersonPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retailer_person_place_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("address_rate_class", models.CharField(max_length=255)),
                ("address_1", models.CharField(max_length=255)),
                ("address_2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("day_phone", models.CharField(max_length=255)),
                ("night_phone", models.CharField(max_length=255)),
                ("partner_person_place_id", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retailers.retailer",
                    ),
                ),
            ],
        ),
    ]
