# Generated by Django 3.2.14 on 2023-12-11 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("retailer_purchase_order_items", "0004_pendinginventorysubtraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerPurchaseOrderReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_qty",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name=django.core.validators.MinValueValidator(1),
                    ),
                ),
                ("unbroken_qty", models.PositiveIntegerField(default=0)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Courtesy Return", "Courtesy Return"),
                            ("Ordered Wrong Item", "Ordered Wrong Item"),
                            ("Warranty", "Warranty"),
                            ("Changed Mind", "Changed Mind"),
                            ("Received Wrong Item", "Received Wrong Item"),
                            ("Retal", "Retal"),
                            ("Damaged", "Damaged"),
                            ("Defective", "Defective"),
                            ("Arrived Too Late", "Arrived Too Late"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_returns",
                        to="retailer_purchase_order_items.retailerpurchaseorderitem",
                    ),
                ),
            ],
        ),
    ]
