# Generated by Django 3.2.14 on 2023-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "retailer_purchase_order_return_items",
            "0002_retailerpurchaseorderreturnitem_order_return",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="retailerpurchaseorderreturnitem",
            old_name="unbroken_qty",
            new_name="damaged_qty",
        ),
        migrations.AlterField(
            model_name="retailerpurchaseorderreturnitem",
            name="return_qty",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
