# Generated by Django 3.2.14 on 2023-07-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boxes", "0004_alter_box_max_quantity"),
        ("retailer_purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "box",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boxes.box",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_packages",
                        to="retailer_purchase_orders.retailerpurchaseorder",
                    ),
                ),
            ],
        ),
    ]
