# Generated by Django 4.2.3 on 2023-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_package", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpackage",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderpackage",
            name="length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderpackage",
            name="width",
            field=models.IntegerField(default=0),
        ),
    ]
