# Generated by Django 3.2.14 on 2023-07-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_package", "0002_orderpackage_height_orderpackage_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpackage",
            name="dimension_unit",
            field=models.CharField(default="cm", max_length=100),
        ),
        migrations.AddField(
            model_name="orderpackage",
            name="weight",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="orderpackage",
            name="weight_unit",
            field=models.CharField(default="lb", max_length=100),
        ),
    ]
