from django.db import models


class Permissions(models.TextChoices):
    UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION"
    DELETE_ORGANIZATION = "DELETE_ORGANIZATION"
    READ_MEMBER = "READ_MEMBER"
    INVITE_MEMBER = "INVITE_MEMBER"
    REMOVE_MEMBER = "REMOVE_MEMBER"
    UPDATE_MEMBER_ROLE = "UPDATE_MEMBER_ROLE"
    CREATE_ROLE = "CREATE_ROLE"
    UPDATE_ROLE = "UPDATE_ROLE"
    DELETE_ROLE = "DELETE_ROLE"
    READ_ROLE = "READ_ROLE"
    CREATE_RETAILER = "CREATE_RETAILER"
    UPDATE_RETAILER = "UPDATE_RETAILER"
    DELETE_RETAILER = "DELETE_RETAILER"
    READ_RETAILER = "READ_RETAILER"
