# Generated by Django 3.2.14 on 2023-09-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qbo_unhandled_data", "0001_initial_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qbounhandleddata",
            name="action",
            field=models.CharField(
                choices=[("CREATE", "CREATE"), ("UPDATE", "UPDATE")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="qbounhandleddata",
            name="model",
            field=models.CharField(
                choices=[("RETAILER", "RETAILER"), ("PRODUCT", "PRODUCT")],
                max_length=255,
            ),
        ),
    ]
