# Generated by Django 3.2.14 on 2023-09-28 07:42

from django.db import migrations
from selleraxis.products.models import Product
from selleraxis.retailers.models import Retailer
from selleraxis.qbo_unhandled_data.models import QBOUnhandledData


def sync_unhandled_data(apps, schema_editor):
    product_list = Product.objects.filter(qbo_product_id=None)
    retailer_list = Retailer.objects.filter(qbo_customer_ref_id=1)
    qbo_unhandled_data = []
    for product_item in product_list:
        if product_item.product_series is not None:
            data = QBOUnhandledData(
                model=QBOUnhandledData.Model.PRODUCT.value,
                action=QBOUnhandledData.Action.CREATE.value,
                object_id=product_item.id,
                status=QBOUnhandledData.Status.UNHANDLED.value,
                organization=product_item.product_series.organization,
            )
            qbo_unhandled_data.append(data)

    for retailer_item in retailer_list:
        data = QBOUnhandledData(
            model=QBOUnhandledData.Model.RETAILER.value,
            action=QBOUnhandledData.Action.CREATE.value,
            object_id=retailer_item.id,
            status=QBOUnhandledData.Status.UNHANDLED.value,
            organization=retailer_item.organization,
        )
        qbo_unhandled_data.append(data)
    QBOUnhandledData.objects.bulk_create(qbo_unhandled_data)


class Migration(migrations.Migration):
    dependencies = [
        ("qbo_unhandled_data", "0002_auto_20230928_0330"),
    ]

    operations = [migrations.RunPython(sync_unhandled_data)]
