# Generated by Django 3.2.14 on 2023-07-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_alias", "0002_auto_20230713_0218"),
    ]

    operations = [
        migrations.AddField(
            model_name="productalias",
            name="is_live_data",
            field=models.BooleanField(default=False),
        ),
    ]
