# Generated by Django 4.2.3 on 2023-07-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_alias", "0003_productalias_is_live_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="productalias",
            name="sku_quantity",
            field=models.IntegerField(default=1),
        ),
    ]
