# Generated by Django 3.2.14 on 2023-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_alias", "0004_productalias_sku_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="productalias",
            name="upc",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
