# Generated by Django 3.2.14 on 2023-11-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_alias", "0005_productalias_upc"),
    ]

    operations = [
        migrations.AddField(
            model_name="productalias",
            name="availability",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Unavailable", "Unavailable"),
                    ("Discontinued", "Discontinued"),
                    ("Guaranteed", "Guaranteed"),
                ],
                default="Available",
                max_length=255,
            ),
        ),
    ]
