# Generated by Django 3.2.14 on 2023-07-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("package_rules", "0003_auto_20230714_0835"),
        ("barcode_sizes", "0002_barcodesize_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("dimension_unit", models.CharField(max_length=100)),
                ("max_quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barcode_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="barcode_sizes.barcodesize",
                    ),
                ),
                (
                    "package_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="package_rules.packagerule",
                    ),
                ),
            ],
        ),
    ]
