# Generated by Django 3.2.14 on 2023-07-20 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_auto_20230706_0702"),
        ("boxes", "0002_remove_box_package_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="box",
            name="max_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
