# Generated by Django 3.2.14 on 2023-07-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boxes", "0003_auto_20230720_0215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="max_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
