# Generated by Django 3.2.14 on 2023-08-01 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boxes", "0004_alter_box_max_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="box",
            name="max_quantity",
        ),
    ]
