# Generated by Django 3.2.14 on 2023-08-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_warehouses", "0002_alter_retailerwarehouse_retailer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="retailerwarehouse",
            old_name="address",
            new_name="address_1",
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="address_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="postal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
