# Generated by Django 3.2.14 on 2023-08-10 01:46

from django.db import migrations, models
import django.db.models.deletion
from selleraxis.retailer_warehouses.models import RetailerWarehouse


def migrate_organization_from_retailer(apps, schema_editor):
    warehouses = RetailerWarehouse.objects.all()
    for warehouse in warehouses:
        warehouse.organization_id = warehouse.retailer.organization.pk

    RetailerWarehouse.objects.bulk_update(
        warehouses, fields=["organization_id"], batch_size=1000
    )


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_auto_20230706_0702"),
        ("retailer_warehouses", "0002_alter_retailerwarehouse_retailer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="retailerwarehouse",
            old_name="address",
            new_name="address_1",
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="address_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retailer_warehouses_organization",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="postal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(migrate_organization_from_retailer),
    ]
