# Generated by Django 3.2.14 on 2023-08-10 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_warehouses", "0003_auto_20230810_0146"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailerwarehouse",
            name="retailer",
        ),
    ]
