# Generated by Django 3.2.14 on 2023-08-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_set_default_email"),
        ("retailer_warehouses", "0003_auto_20230811_0302"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailerwarehouse",
            name="retailer",
        ),
        migrations.AddField(
            model_name="retailerwarehouse",
            name="organization",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse",
                to="organizations.organization",
            ),
        ),
    ]
