# Generated by Django 3.2.14 on 2023-07-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_carriers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailercarrier",
            name="account_number",
            field=models.CharField(default="", max_length=255),
        ),
    ]
