# Generated by Django 3.2.14 on 2023-08-31 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_service_types", "0001_initial"),
        ("retailer_carriers", "0005_auto_20230816_0329"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailercarrier",
            name="default_service_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carrier_service_type",
                to="shipping_service_types.shippingservicetype",
            ),
        ),
    ]
