# Generated by Django 3.2.14 on 2023-07-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("package_rules", "0001_initial"),
        ("organizations", "0002_organization_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("unit_of_measure", models.CharField(max_length=100)),
                ("available", models.CharField(max_length=100)),
                ("upc", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("unit_cost", models.FloatField()),
                ("qty_on_hand", models.IntegerField()),
                ("qty_reserve", models.IntegerField()),
                ("image", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "package_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="package_rules.packagerule",
                    ),
                ),
            ],
        ),
    ]
