# Generated by Django 3.2.14 on 2023-03-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("package_rules", "0001_initial"),
        ("barcode_sizes", "0001_initial"),
        ("product_types", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_merch_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_url", models.TextField()),
                ("cost", models.FloatField()),
                ("sale_price", models.FloatField()),
                ("model_series", models.CharField(max_length=255)),
                ("master_sku", models.CharField(max_length=255)),
                ("child_sku", models.CharField(max_length=255)),
                ("upc", models.CharField(max_length=255)),
                ("sku_quantity", models.IntegerField()),
                ("weight", models.FloatField()),
                ("weight_unit", models.CharField(max_length=255)),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("dimension_unit", models.CharField(max_length=255)),
                ("qbo_item_id", models.CharField(max_length=255)),
                ("commodity_code", models.CharField(max_length=255)),
                ("country_of_manufacture", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barcode_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="barcode_sizes.barcodesize",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "package_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="package_rules.packagerule",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_types.producttype",
                    ),
                ),
            ],
        ),
    ]
