# Generated by Django 3.2.14 on 2023-07-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="qty_pending",
            field=models.IntegerField(default=0),
        ),
    ]
