# Generated by Django 4.1.7 on 2023-04-17 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=[], size=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.TextField(default=""),
        ),
    ]
