# Generated by Django 3.2.14 on 2023-07-19 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_qty_pending"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="package_rule",
        ),
    ]
