# Generated by Django 3.2.14 on 2023-07-20 07:32

from django.db import migrations, models
from selleraxis.products.models import Product, ProductSeries
from selleraxis.organizations.models import Organization
import django.db.models.deletion


def generate_product_organization(apps, schema_editor):
    organizations = Organization.objects.all()
    object_list = [
        ProductSeries(series=organization.name, organization_id=organization.pk)
        for organization in organizations
    ]

    product_series_list = ProductSeries.objects.bulk_create(object_list)
    product_series_dict = {
        product_series.organization_id: product_series
        for product_series in product_series_list
    }
    update_object_list = []
    products = Product.objects.all()
    for product in products:
        product_series = product_series_dict.get(product.organization_id, None)
        if product_series:
            product.product_series_id = product_series.pk
            update_object_list.append(product)

    Product.objects.bulk_update(update_object_list, ["product_series_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_product_package_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_series.productseries",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="volume_unit",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(generate_product_organization),
    ]
