# Generated by Django 3.2.14 on 2023-07-20 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_series"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="organization",
        ),
    ]
