# Generated by Django 3.2.14 on 2023-07-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_series", "0001_initial"),
        ("products", "0005_remove_product_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product_series.productseries",
            ),
        ),
    ]
