# Generated by Django 4.2.3 on 2023-07-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_product_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                choices=[("LB", "lb"), ("LBS", "lbs"), ("KG", "kg")],
                default="lb",
                max_length=255,
            ),
        ),
    ]
