# Generated by Django 3.2.14 on 2023-11-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_sync_token_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inv_start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
