# Generated by Django 3.2.14 on 2023-10-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_inv_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="live_inv_start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="live_qbo_product_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="live_sync_token",
            field=models.IntegerField(null=True),
        ),
    ]
