# Generated by Django 3.2.14 on 2023-11-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_product_add_live_qbo_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="live_inv_start_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="live_qbo_product_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="live_sync_token",
        ),
    ]
