# Generated by Django 3.2.14 on 2023-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_product_remove_live_qbo_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="qbo_account_ref_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="qbo_account_ref_name",
            field=models.CharField(
                blank=True, max_length=255, default="Inventory Asset"
            ),
        ),
    ]
