# Generated by Django 3.2.14 on 2023-12-14 08:49

from django.db import migrations, models


def update_account_ref_info(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(
        product_series__organization__sandbox_organization__isnull=True
    ).update(
        qbo_account_ref_id=81,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_alter_product_add_account_ref_info"),
    ]

    operations = [
        migrations.RunPython(update_account_ref_info),
    ]
