# Generated by Django 3.2.14 on 2023-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_product_update_account_ref_info_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expense_account_ref_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="expense_account_ref_name",
            field=models.CharField(
                blank=True, default="Cost of Goods Sold", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="income_account_ref_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="income_account_ref_name",
            field=models.CharField(
                blank=True, default="Sales of Product Income", max_length=255
            ),
        ),
    ]
