# Generated by Django 3.2.14 on 2023-06-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sftp_host", models.CharField(max_length=255)),
                ("sftp_username", models.CharField(max_length=255)),
                ("sftp_password", models.CharField(max_length=255)),
                ("purchase_orders_sftp_directory", models.CharField(max_length=255)),
                ("acknowledgment_sftp_directory", models.CharField(max_length=255)),
                ("confirm_sftp_directory", models.CharField(max_length=255)),
                ("inventory_sftp_directory", models.CharField(max_length=255)),
                ("invoice_sftp_directory", models.CharField(max_length=255)),
                ("return_sftp_directory", models.CharField(max_length=255)),
                ("payment_sftp_directory", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
