# Generated by Django 3.2.14 on 2023-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailer",
            name="acknowledgment_sftp_directory",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="confirm_sftp_directory",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="inventory_sftp_directory",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="invoice_sftp_directory",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="payment_sftp_directory",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="purchase_orders_sftp_directory",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="return_sftp_directory",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="sftp_host",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="sftp_password",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="sftp_username",
        ),
        migrations.AddField(
            model_name="retailer",
            name="type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
