# Generated by Django 3.2.14 on 2023-07-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0003_alter_retailer_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="merchant_id",
            field=models.CharField(default="lowes", max_length=255),
        ),
    ]
