# Generated by Django 3.2.14 on 2023-08-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0004_retailer_merchant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="qbo_customer_ref_id",
            field=models.CharField(default="1", max_length=100),
        ),
    ]
