# Generated by Django 3.2.14 on 2023-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0005_retailer_qbo_customer_ref_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="qbo_customer_ref_id",
            field=models.CharField(blank=True, default="1", max_length=100),
        ),
    ]
