# Generated by Django 3.2.14 on 2023-08-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0006_alter_retailer_qbo_customer_ref_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="default_carrier",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="default_warehouse",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
