# Generated by Django 3.2.14 on 2023-08-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_carriers", "0005_auto_20230816_0329"),
        ("retailer_warehouses", "0004_auto_20230814_0814"),
        ("retailers", "0008_retailer_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="default_carrier",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retailer_carrier",
                to="retailer_carriers.retailercarrier",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="default_warehouse",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retailer_organization",
                to="retailer_warehouses.retailerwarehouse",
            ),
        ),
    ]
