# Generated by Django 3.2.14 on 2023-08-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gs1", "0001_initial"),
        ("retailers", "0010_auto_20230818_0803"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="default_gs1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retailer",
                to="gs1.gs1",
            ),
        ),
    ]
