# Generated by Django 3.2.14 on 2023-09-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
        ("retailers", "0011_retailer_default_gs1"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="ship_from_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retailer_address",
                to="addresses.address",
            ),
        ),
    ]
