# Generated by Django 3.2.14 on 2023-09-05 09:39

from django.db import migrations, models
import django.db.models.deletion


def handle_ship_from_address_null(apps, schema_editor):
    Retailer = apps.get_model("retailers", "Retailer")
    Address = apps.get_model("addresses", "Address")
    for retailer in Retailer.objects.filter(ship_from_address__isnull=True):
        new_address = Address(organization_id=retailer.organization_id)
        new_address.save()
        retailer.ship_from_address_id = new_address.id
        retailer.save()


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
        ("retailers", "0012_retailer_ship_from_address"),
    ]

    operations = [
        migrations.RunPython(handle_ship_from_address_null),
    ]
