# Generated by Django 3.2.14 on 2023-09-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_ref_type", "0001_initial"),
        ("retailers", "0013_retailer_handle_ship_from_address_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_1_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_ref_1_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_1_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_2_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_ref_2_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_2_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_3_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_ref_3_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_3_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_4_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_ref_4_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_4_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_5_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_ref_5_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="shipping_ref_5_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
