# Generated by Django 3.2.14 on 2023-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0014_auto_20230921_0502"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="sync_token",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="qbo_customer_ref_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
