# Generated by Django 3.2.14 on 2023-10-03 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_ref_type", "0001_initial"),
        ("retailers", "0015_add_sync_toke_to_retailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="shipping_ref_1_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_ref_1_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="shipping_ref_2_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_ref_2_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="shipping_ref_3_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_ref_3_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="shipping_ref_4_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_ref_4_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="shipping_ref_5_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_ref_5_type",
                to="shipping_ref_type.shippingreftype",
            ),
        ),
    ]
