# Generated by Django 3.2.14 on 2023-10-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0016_auto_20231003_0045"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="remit_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
