# Generated by Django 3.2.14 on 2023-10-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0017_retailer_remit_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="live_qbo_customer_ref_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="retailer",
            name="live_sync_token",
            field=models.IntegerField(null=True),
        ),
    ]
