# Generated by Django 3.2.14 on 2023-11-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0018_retailer_add_live_qbo_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailer",
            name="live_qbo_customer_ref_id",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="live_sync_token",
        ),
    ]
