# Generated by Django 3.2.14 on 2023-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="live_doc_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="live_invoice_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="doc_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
