# Generated by Django 3.2.14 on 2023-03-30 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization_members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="roles.role",
            ),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
