# Generated by Django 3.2.14 on 2023-06-30 04:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("UPDATE_ORGANIZATION", "Update Organization"),
                                ("DELETE_ORGANIZATION", "Delete Organization"),
                                ("READ_MEMBER", "Read Member"),
                                ("INVITE_MEMBER", "Invite Member"),
                                ("REMOVE_MEMBER", "Remove Member"),
                                ("UPDATE_MEMBER_ROLE", "Update Member Role"),
                                ("CREATE_ROLE", "Create Role"),
                                ("UPDATE_ROLE", "Update Role"),
                                ("DELETE_ROLE", "Delete Role"),
                                ("READ_ROLE", "Read Role"),
                                ("CREATE_RETAILER", "Create Retailer"),
                                ("UPDATE_RETAILER", "Update Retailer"),
                                ("DELETE_RETAILER", "Delete Retailer"),
                                ("READ_RETAILER", "Read Retailer"),
                                ("CREATE_RETAILER_PARTNER", "Create Retailer Partner"),
                                ("UPDATE_RETAILER_PARTNER", "Update Retailer Partner"),
                                ("DELETE_RETAILER_PARTNER", "Delete Retailer Partner"),
                                ("READ_RETAILER_PARTNER", "Read Retailer Partner"),
                                (
                                    "CREATE_RETAILER_ORDER_BATCH",
                                    "Create Retailer Order Batch",
                                ),
                                (
                                    "UPDATE_RETAILER_ORDER_BATCH",
                                    "Update Retailer Order Batch",
                                ),
                                (
                                    "DELETE_RETAILER_ORDER_BATCH",
                                    "Delete Retailer Order Batch",
                                ),
                                (
                                    "READ_RETAILER_ORDER_BATCH",
                                    "Read Retailer Order Batch",
                                ),
                                (
                                    "CREATE_RETAILER_PARTICIPATING_PARTY",
                                    "Create Retailer Participating Party",
                                ),
                                (
                                    "UPDATE_RETAILER_PARTICIPATING_PARTY",
                                    "Update Retailer Participating Party",
                                ),
                                (
                                    "DELETE_RETAILER_PARTICIPATING_PARTY",
                                    "Delete Retailer Participating Party",
                                ),
                                (
                                    "READ_RETAILER_PARTICIPATING_PARTY",
                                    "Read Retailer Participating Party",
                                ),
                                (
                                    "CREATE_RETAILER_PERSON_PLACE",
                                    "Create Retailer Person Place",
                                ),
                                (
                                    "UPDATE_RETAILER_PERSON_PLACE",
                                    "Update Retailer Person Place",
                                ),
                                (
                                    "DELETE_RETAILER_PERSON_PLACE",
                                    "Delete Retailer Person Place",
                                ),
                                (
                                    "READ_RETAILER_PERSON_PLACE",
                                    "Read Retailer Person Place",
                                ),
                                (
                                    "CREATE_RETAILER_PURCHASE_ORDER",
                                    "Create Retailer Purchase Order",
                                ),
                                (
                                    "UPDATE_RETAILER_PURCHASE_ORDER",
                                    "Update Retailer Purchase Order",
                                ),
                                (
                                    "DELETE_RETAILER_PURCHASE_ORDER",
                                    "Delete Retailer Purchase Order",
                                ),
                                (
                                    "READ_RETAILER_PURCHASE_ORDER",
                                    "Read Retailer Purchase Order",
                                ),
                                (
                                    "IMPORT_RETAILER_PURCHASE_ORDER",
                                    "Import Retailer Purchase Order",
                                ),
                                (
                                    "CREATE_RETAILER_PURCHASE_ORDER_ITEM",
                                    "Create Retailer Purchase Order Item",
                                ),
                                (
                                    "UPDATE_RETAILER_PURCHASE_ORDER_ITEM",
                                    "Update Retailer Purchase Order Item",
                                ),
                                (
                                    "DELETE_RETAILER_PURCHASE_ORDER_ITEM",
                                    "Delete Retailer Purchase Order Item",
                                ),
                                (
                                    "READ_RETAILER_PURCHASE_ORDER_ITEM",
                                    "Read Retailer Purchase Order Item",
                                ),
                                ("CREATE_PACKAGE_RULE", "Create Package Rule"),
                                ("UPDATE_PACKAGE_RULE", "Update Package Rule"),
                                ("DELETE_PACKAGE_RULE", "Delete Package Rule"),
                                ("READ_PACKAGE_RULE", "Read Package Rule"),
                                ("CREATE_BARCODE_SIZE", "Create Barcode Size"),
                                ("UPDATE_BARCODE_SIZE", "Update Barcode Size"),
                                ("DELETE_BARCODE_SIZE", "Delete Barcode Size"),
                                ("READ_BARCODE_SIZE", "Read Barcode Size"),
                                ("CREATE_PRODUCT_TYPE", "Create Product Type"),
                                ("UPDATE_PRODUCT_TYPE", "Update Product Type"),
                                ("DELETE_PRODUCT_TYPE", "Delete Product Type"),
                                ("READ_PRODUCT_TYPE", "Read Product Type"),
                            ],
                            max_length=255,
                        ),
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
