# Generated by Django 3.2.14 on 2023-03-30 04:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("UPDATE_ORGANIZATION", "Update Organization"),
                                ("DELETE_ORGANIZATION", "Delete Organization"),
                                ("READ_MEMBER", "Read Member"),
                                ("INVITE_MEMBER", "Invite Member"),
                                ("REMOVE_MEMBER", "Remove Member"),
                                ("UPDATE_MEMBER_ROLE", "Update Member Role"),
                                ("CREATE_ROLE", "Create Role"),
                                ("UPDATE_ROLE", "Update Role"),
                                ("DELETE_ROLE", "Delete Role"),
                                ("READ_ROLE", "Read Role"),
                                ("CREATE_RETAILER", "Create Retailer"),
                                ("UPDATE_RETAILER", "Update Retailer"),
                                ("DELETE_RETAILER", "Delete Retailer"),
                                ("READ_RETAILER", "Read Retailer"),
                                ("CREATE_RETAILER_PARTNER", "Create Retailer Partner"),
                                ("UPDATE_RETAILER_PARTNER", "Update Retailer Partner"),
                                ("DELETE_RETAILER_PARTNER", "Delete Retailer Partner"),
                                ("READ_RETAILER_PARTNER", "Read Retailer Partner"),
                            ],
                            max_length=255,
                        ),
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
