# Generated by Django 3.2.14 on 2023-03-30 02:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("UPDATE_ORGANIZATION", "Update Organization"),
                        ("DELETE_ORGANIZATION", "Delete Organization"),
                        ("READ_MEMBER", "Read Member"),
                        ("INVITE_MEMBER", "Invite Member"),
                        ("REMOVE_MEMBER", "Remove Member"),
                        ("UPDATE_MEMBER_ROLE", "Update Member Role"),
                        ("CREATE_ROLE", "Create Role"),
                        ("UPDATE_ROLE", "Update Role"),
                        ("DELETE_ROLE", "Delete Role"),
                        ("READ_ROLE", "Read Role"),
                        ("CREATE_RETAILER", "Create Retailer"),
                        ("UPDATE_RETAILER", "Update Retailer"),
                        ("DELETE_RETAILER", "Delete Retailer"),
                        ("READ_RETAILER", "Read Retailer"),
                    ],
                    max_length=255,
                ),
                size=None,
            ),
        ),
    ]
