# Generated by Django 3.2.14 on 2023-03-30 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0005_alter_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("UPDATE_ORGANIZATION", "Update Organization"),
                        ("DELETE_ORGANIZATION", "Delete Organization"),
                        ("READ_MEMBER", "Read Member"),
                        ("INVITE_MEMBER", "Invite Member"),
                        ("REMOVE_MEMBER", "Remove Member"),
                        ("UPDATE_MEMBER_ROLE", "Update Member Role"),
                        ("CREATE_ROLE", "Create Role"),
                        ("UPDATE_ROLE", "Update Role"),
                        ("DELETE_ROLE", "Delete Role"),
                        ("READ_ROLE", "Read Role"),
                        ("CREATE_RETAILER", "Create Retailer"),
                        ("UPDATE_RETAILER", "Update Retailer"),
                        ("DELETE_RETAILER", "Delete Retailer"),
                        ("READ_RETAILER", "Read Retailer"),
                        ("CREATE_RETAILER_PARTNER", "Create Retailer Partner"),
                        ("UPDATE_RETAILER_PARTNER", "Update Retailer Partner"),
                        ("DELETE_RETAILER_PARTNER", "Delete Retailer Partner"),
                        ("READ_RETAILER_PARTNER", "Read Retailer Partner"),
                        ("CREATE_RETAILER_ORDER_BATCH", "Create Retailer Order Batch"),
                        ("UPDATE_RETAILER_ORDER_BATCH", "Update Retailer Order Batch"),
                        ("DELETE_RETAILER_ORDER_BATCH", "Delete Retailer Order Batch"),
                        ("READ_RETAILER_ORDER_BATCH", "Read Retailer Order Batch"),
                        (
                            "CREATE_RETAILER_PARTICIPATING_PARTY",
                            "Create Retailer Participating Party",
                        ),
                        (
                            "UPDATE_RETAILER_PARTICIPATING_PARTY",
                            "Update Retailer Participating Party",
                        ),
                        (
                            "DELETE_RETAILER_PARTICIPATING_PARTY",
                            "Delete Retailer Participating Party",
                        ),
                        (
                            "READ_RETAILER_PARTICIPATING_PARTY",
                            "Read Retailer Participating Party",
                        ),
                        (
                            "CREATE_RETAILER_PERSON_PLACE",
                            "Create Retailer Person Place",
                        ),
                        (
                            "UPDATE_RETAILER_PERSON_PLACE",
                            "Update Retailer Person Place",
                        ),
                        (
                            "DELETE_RETAILER_PERSON_PLACE",
                            "Delete Retailer Person Place",
                        ),
                        ("READ_RETAILER_PERSON_PLACE", "Read Retailer Person Place"),
                        (
                            "CREATE_RETAILER_PURCHASE_ORDER",
                            "Create Retailer Purchase Order",
                        ),
                        (
                            "UPDATE_RETAILER_PURCHASE_ORDER",
                            "Update Retailer Purchase Order",
                        ),
                        (
                            "DELETE_RETAILER_PURCHASE_ORDER",
                            "Delete Retailer Purchase Order",
                        ),
                        (
                            "READ_RETAILER_PURCHASE_ORDER",
                            "Read Retailer Purchase Order",
                        ),
                        (
                            "CREATE_RETAILER_PURCHASE_ORDER_ITEM",
                            "Create Retailer Purchase Order Item",
                        ),
                        (
                            "UPDATE_RETAILER_PURCHASE_ORDER_ITEM",
                            "Update Retailer Purchase Order Item",
                        ),
                        (
                            "DELETE_RETAILER_PURCHASE_ORDER_ITEM",
                            "Delete Retailer Purchase Order Item",
                        ),
                        (
                            "READ_RETAILER_PURCHASE_ORDER_ITEM",
                            "Read Retailer Purchase Order Item",
                        ),
                    ],
                    max_length=255,
                ),
                size=None,
            ),
        ),
    ]
