# Generated by Django 3.2.14 on 2023-09-25 06:41

from django.db import migrations
from selleraxis.roles.models import Role
from selleraxis.permissions.models import Permissions


def migrate_update_role_admin(apps, schema_editor):
    permissions = [permission.value for permission in Permissions]
    Role.objects.filter(name="Admin").update(permissions=permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0017_alter_role_permissions"),
    ]

    operations = [migrations.RunPython(migrate_update_role_admin)]
