# Generated by Django 3.2.14 on 2023-12-11 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("retailer_purchase_order_returns", "0001_initial"),
        ("retailer_purchase_order_return_notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorderreturnnote",
            name="order_return",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="retailer_purchase_order_returns.retailerpurchaseorderreturn",
            ),
        ),
        migrations.AddField(
            model_name="retailerpurchaseorderreturnnote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_return_note_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
