# Generated by Django 3.2.14 on 2023-08-12 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_auto_20230706_0702"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="sscc_prefix",
            field=models.CharField(
                default="",
                max_length=9,
                validators=[django.core.validators.MinLengthValidator(7)],
            ),
        ),
    ]
