# Generated by Django 3.2.14 on 2023-08-12 08:03

from django.db import migrations
from django.db.models import Subquery, OuterRef

from selleraxis.organizations.models import Organization
from selleraxis.users.models import User


def set_default_email(apps, schema_editor):
    Organization.objects.filter(email="").update(
        email=Subquery(
            User.objects.filter(pk=OuterRef("created_by")).values("email")[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_organization_sscc_prefix"),
    ]

    operations = [migrations.RunPython(set_default_email)]
