# Generated by Django 3.2.14 on 2023-08-16 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_set_default_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="sscc_prefix",
            new_name="gs1",
        ),
    ]
