# Generated by Django 3.2.14 on 2023-08-18 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_rename_sscc_prefix_organization_gs1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="gs1",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                validators=[django.core.validators.MinLengthValidator(7)],
            ),
        ),
    ]
