# Generated by Django 3.2.14 on 2023-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_organization_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_sandbox",
            field=models.BooleanField(default=True),
        ),
    ]
