# Generated by Django 3.2.14 on 2023-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_organization_add_live_qbo_token_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="live_qbo_access_token",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="live_qbo_access_token_exp_time",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="live_qbo_refresh_token",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="live_qbo_refresh_token_exp_time",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="live_realm_id",
        ),
        migrations.AddField(
            model_name="organization",
            name="qbo_user_uuid",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
