# Generated by Django 3.2.14 on 2023-11-27 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_organization_remove_live_qbo_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="sandbox_organization",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prod_organization",
                to="organizations.organization",
            ),
        ),
    ]
