# Generated by Django 3.2.14 on 2023-11-27 02:04

from django.db import migrations, models
import django.db.models.deletion


def create_org_prod(apps, schema_editor):
    # get all order
    Organization = apps.get_model("organizations", "Organization")
    list_org = Organization.objects.all().prefetch_related("roles")
    for organization in list_org:
        new_organization = Organization(
            name=organization.name,
            avatar=organization.avatar,
            description=organization.description,
            timezone=organization.timezone,
            address=organization.address,
            email=organization.email,
            phone=organization.phone,
            status=organization.status,
            sandbox_organization=organization,
            created_by=organization.created_by,
        )
        new_organization.save()
        organization.roles.all().update(organization_id=new_organization.id)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_organization_sandbox_organization"),
    ]

    operations = [
        migrations.RunPython(create_org_prod),
    ]
