# Generated by Django 3.2.14 on 2023-11-27 02:04

from django.db import migrations, models
import django.db.models.deletion


def update_org_is_sandbox(apps, schema_editor):
    # get all order
    Organization = apps.get_model("organizations", "Organization")
    list_org = Organization.objects.filter(sandbox_organization__isnull=False)
    for organization in list_org:
        sandbox_organization = organization.sandbox_organization
        sandbox_organization.is_sandbox = organization.is_sandbox
        sandbox_organization.save()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0015_organization_create_pod_organization"),
    ]

    operations = [
        migrations.RunPython(update_org_is_sandbox),
    ]
