# Generated by Django 3.2.14 on 2023-10-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("retailer_queue_histories", "0005_alter_retailerqueuehistory_label"),
        ("retailer_purchase_orders", "0021_alter_retailerpurchaseorder_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerPurchaseOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Opened", "Opened"),
                            ("Acknowledged", "Acknowledged"),
                            ("Shipped", "Shipped"),
                            ("Shipment Confirmed", "Shipment Confirmed"),
                            ("Invoiced", "Invoiced"),
                            ("Invoice Confirmed", "Invoice Confirmed"),
                            ("Cancelled", "Cancelled"),
                            ("Bypassed Acknowledge", "Bypassed Acknowledge"),
                            ("Backorder", "Backorder"),
                        ],
                        default="Opened",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_history",
                        to="retailer_purchase_orders.retailerpurchaseorder",
                    ),
                ),
                (
                    "queue_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_queue_history",
                        to="retailer_queue_histories.retailerqueuehistory",
                    ),
                ),
            ],
        ),
    ]
