# Generated by Django 3.2.14 on 2023-06-30 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("retailers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retailer_partner_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("role_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retailers.retailer",
                    ),
                ),
            ],
        ),
    ]
