# Generated by Django 3.2.14 on 2023-07-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_package", "0001_initial"),
        ("order_item_package", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitempackage",
            name="package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item_packages",
                to="order_package.orderpackage",
            ),
        ),
    ]
