# Generated by Django 3.2.14 on 2023-07-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("retailers", "0002_auto_20230706_0832"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerQueueHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, default=None, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("COMPLETE", "COMPLETE"),
                            ("NOT_FOUND", "NOT_FOUND"),
                        ],
                        default="NOT_FOUND",
                        max_length=255,
                    ),
                ),
                (
                    "result_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retailer_queue_history",
                        to="retailers.retailer",
                    ),
                ),
            ],
        ),
    ]
