# Generated by Django 3.2.14 on 2023-07-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_queue_histories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerqueuehistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("COMPLETED", "COMPLETED"),
                    ("NOT_FOUND", "NOT_FOUND"),
                    ("FAILED", "FAILED"),
                ],
                default="NOT_FOUND",
                max_length=255,
            ),
        ),
    ]
