# Generated by Django 3.2.14 on 2023-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_queue_histories", "0002_alter_retailerqueuehistory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerqueuehistory",
            name="label",
            field=models.CharField(
                choices=[
                    ("ACKNOWLEDGMENT", "ACKNOWLEDGMENT"),
                    ("CONFIRM", "CONFIRM"),
                    ("INVENTORY", "INVENTORY"),
                    ("INVOICE", "INVOICE"),
                    ("RETURN", "RETURN"),
                    ("PAYMENT", "PAYMENT"),
                ],
                default="INVENTORY",
                max_length=255,
            ),
        ),
    ]
