# Generated by Django 3.2.14 on 2023-10-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailer_queue_histories", "0004_alter_retailerqueuehistory_result_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerqueuehistory",
            name="label",
            field=models.CharField(
                choices=[
                    ("ACKNOWLEDGMENT", "ACKNOWLEDGMENT"),
                    ("CONFIRM", "CONFIRM"),
                    ("INVENTORY", "INVENTORY"),
                    ("INVOICE", "INVOICE"),
                    ("RETURN", "RETURN"),
                    ("PAYMENT", "PAYMENT"),
                    ("BACKORDER", "BACKORDER"),
                ],
                default="INVENTORY",
                max_length=255,
            ),
        ),
    ]
