# Generated by Django 4.1.7 on 2023-03-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailer_purchase_order_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerpurchaseorderitem",
            name="po_line_data",
            field=models.JSONField(null=True),
        ),
    ]
