# Generated by Django 3.2.14 on 2023-08-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_purchase_order_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerpurchaseorderitem",
            name="unit_cost",
            field=models.FloatField(max_length=255),
        ),
    ]
