# Generated by Django 3.2.14 on 2023-08-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "retailer_purchase_order_items",
            "0002_alter_retailerpurchaseorderitem_unit_cost",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorderitem",
            name="cancel_reason",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
