# Generated by Django 3.2.14 on 2023-07-27 09:02

from django.db import migrations

from selleraxis.service_api.models import ServiceAPI, ServiceAPIAction
from selleraxis.services.models import Services, ServiceType


def create_default_fedex_service(apps, schema_editor):
    service = Services(
        name="FEDEX",
        type=ServiceType.SHIPPING,
        general_client_id="",
        general_client_secret="",
    )
    service.save()

    # FedEx auth API detail
    fedex_auth_sandbox_url = "https://apis-sandbox.fedex.com/oauth/token"

    fedex_auth_production_url = "https://apis.fedex.com/oauth/token"

    fedex_auth_method = "POST"

    fedex_auth_header = """{
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "application/json",
        "x-merchant-id": "{{client_id}}"
    }"""

    fedex_auth_body = """{
        "grant_type": "client_credentials",
        "client_id": "{{client_id}}",
        "client_secret": "{{client_secret}}"
    }"""

    fedex_auth_response = """{
        "access_token": "{{access_token}}",
        "token_type": "bearer",
        "expires_in": 3599,
        "scope": "CXS-TP"
    }"""

    ServiceAPI(
        action=ServiceAPIAction.LOGIN,
        sandbox_url=fedex_auth_sandbox_url,
        production_url=fedex_auth_production_url,
        method=fedex_auth_method,
        body=fedex_auth_body,
        response=fedex_auth_response,
        header=fedex_auth_header,
        service=service,
    ).save()

    # FedEx address validation API detail
    fedex_validate_address_sandbox_url = (
        "https://apis-sandbox.fedex.com/address/v1/addresses/resolve"
    )

    fedex_validate_address_production_url = (
        "https://apis.fedex.com/address/v1/addresses/resolve"
    )

    fedex_validate_address_method = "POST"

    fedex_validate_address_header = """{
        "Authorization": "Bearer {{access_token}}",
        "Content-Type": "application/json",
        "x-locale": "en_US"
    }"""

    fedex_validate_address_body = """{
        "addressesToValidate": [
            {
                "address": {
                    "streetLines": [
                        "{{address_1}}",
                        "{{address_2}}"
                    ],
                    "city": "{{city}}",
                    "stateOrProvinceCode": "{{state}}",
                    "postalCode": "{{postal_code}}",
                    "countryCode": "{{country}}"
                }
            }
        ]
    }"""

    fedex_validate_address_response = """{
        "address_1": "{{output.resolvedAddresses.0.streetLinesToken.0}}",
        "address_2": "{{output.resolvedAddresses.0.streetLinesToken.1}}",
        "city": "{{output.resolvedAddresses.0.city}}",
        "state": "{{output.resolvedAddresses.0.stateOrProvinceCode}}",
        "postal_code": "{{output.resolvedAddresses.0.postalCode}}",
        "country": "{{output.resolvedAddresses.0.countryCode}}"
    }"""

    ServiceAPI(
        action=ServiceAPIAction.ADDRESS_VALIDATION,
        sandbox_url=fedex_validate_address_sandbox_url,
        production_url=fedex_validate_address_production_url,
        method=fedex_validate_address_method,
        body=fedex_validate_address_body,
        response=fedex_validate_address_response,
        header=fedex_validate_address_header,
        service=service,
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("service_api", "0002_auto_20230727_0859"),
    ]

    operations = [migrations.RunPython(create_default_fedex_service)]
