# Generated by Django 3.2.14 on 2023-08-12 06:32

from django.db import migrations

from selleraxis.service_api.models import ServiceAPI, ServiceAPIAction
from selleraxis.services.models import Services


def create_default_fedex_cancel_shipment_api(apps, schema_editor):
    service = Services.objects.filter(name="FEDEX").first()

    fedex_cancel_shipment_sandbox_url = (
        "https://apis-sandbox.fedex.com/ship/v1/shipments/cancel"
    )

    fedex_cancel_shipment_production_url = (
        "https://apis.fedex.com/ship/v1/shipments/cancel"
    )

    fedex_cancel_shipment_method = "PUT"

    fedex_cancel_shipment_header = """{
        "Authorization": "Bearer {{access_token}}",
        "Content-Type": "application/json",
        "x-locale": "en_US"
    }"""

    fedex_cancel_shipment_body = """{
        "accountNumber": {
            "value": "{{carrier.account_number}}"
        },
        "emailShipment": "false",
        "senderCountryCode": "{{sender_country}}",
        "deletionControl": "DELETE_ALL_PACKAGES",
        "trackingNumber": "{{tracking_number}}"
    }"""

    fedex_cancel_shipment_response = """{
        "status": "{{output.cancelledShipment}}"
    }"""

    ServiceAPI(
        action=ServiceAPIAction.CANCEL_SHIPPING,
        sandbox_url=fedex_cancel_shipment_sandbox_url,
        production_url=fedex_cancel_shipment_production_url,
        method=fedex_cancel_shipment_method,
        body=fedex_cancel_shipment_body,
        response=fedex_cancel_shipment_response,
        header=fedex_cancel_shipment_header,
        service=service,
    ).save()


def create_default_ups_cancel_shipment_api(apps, schema_editor):
    service = Services.objects.filter(name="UPS").first()

    ups_cancel_shipment_sandbox_url = "https://wwwcie.ups.com/api/shipments/v1/void/cancel/{{identification_number}}?trackingnumber={{tracking_number}}"

    ups_cancel_shipment_production_url = "https://wwwcie.ups.com/api/shipments/v1/void/cancel/{{identification_number}}?trackingnumber={{tracking_number}}"

    ups_cancel_shipment_method = "DELETE"

    ups_cancel_shipment_header = """{
        "Authorization": "Bearer {{access_token}}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }"""

    ups_cancel_shipment_body = "{}"

    ups_cancel_shipment_response = """{
        "status": "{{VoidShipmentResponse.Response.ResponseStatus.Code}}"
    }"""

    ServiceAPI(
        action=ServiceAPIAction.CANCEL_SHIPPING,
        sandbox_url=ups_cancel_shipment_sandbox_url,
        production_url=ups_cancel_shipment_production_url,
        method=ups_cancel_shipment_method,
        body=ups_cancel_shipment_body,
        response=ups_cancel_shipment_response,
        header=ups_cancel_shipment_header,
        service=service,
    ).save()


def update_default_ups_shipping_response(apps, schema_editor):
    ups = Services.objects.filter(name="UPS").first()
    ups_service_api = ServiceAPI.objects.filter(service=ups, action="SHIPPING").first()
    ups_service_api.response = """{
        "shipments": {
            "data": {
                "package_document": "{{ShippingLabel.GraphicImage}}",
                "tracking_number": "{{TrackingNumber}}"
            },
            "field": "{{ShipmentResponse.ShipmentResults.PackageResults}}",
            "type": "list|dict"
        },
        "identification_number": "{{ShipmentResponse.ShipmentResults.ShipmentIdentificationNumber}}"
    }"""

    ups_service_api.save()


class Migration(migrations.Migration):
    dependencies = [
        ("service_api", "0009_migrate_ship_from_to_shipping_api"),
    ]

    operations = [
        migrations.RunPython(create_default_fedex_cancel_shipment_api),
        migrations.RunPython(create_default_ups_cancel_shipment_api),
        migrations.RunPython(update_default_ups_shipping_response),
    ]
