# Generated by Django 3.2.14 on 2023-08-21 06:59

from django.db import migrations

from selleraxis.service_api.models import ServiceAPI, ServiceAPIAction
from selleraxis.services.models import Services


def update_ups_shipping_body(apps, schema_editor):
    ups_service = Services.objects.filter(name="UPS").first()
    ups_shipping_api = ServiceAPI.objects.filter(
        service=ups_service.id, action=ServiceAPIAction.SHIPPING
    ).first()
    ups_shipping_api.body = """{
        "ShipmentRequest": {
            "Request": {
                "SubVersion": "1801",
                "RequestOption": "nonvalidate",
                "TransactionReference": {
                    "CustomerContext": ""
                }
            },
            "Shipment": {
                "Description": "Infibrite Shipment",
                "Shipper": {
                    "Name": "{{carrier.shipper.name}}",
                    "AttentionName": "{{carrier.shipper.attention_name}}",
                    "TaxIdentificationNumber": "{{carrier.shipper.tax_identification_number}}",
                    "Phone": {
                        "Number": "{{carrier.shipper.phone}}",
                        "Extension": ""
                    },
                    "ShipperNumber": "{{carrier.shipper.shipper_number}}",
                    "FaxNumber": "{{carrier.shipper.fax_number}}",
                    "Address": {
                        "AddressLine": "{{carrier.shipper.address}}",
                        "City": "{{carrier.shipper.city}}",
                        "StateProvinceCode": "{{carrier.shipper.state}}",
                        "PostalCode": "{{carrier.shipper.postal_code}}",
                        "CountryCode": "{{carrier.shipper.country}}"
                    }
                },
                "ShipTo": {
                    "Name": "{{verified_ship_to.contact_name}}",
                    "AttentionName": "{{verified_ship_to.contact_name}}",
                    "Phone": {
                        "Number": "{{verified_ship_to.phone}}"
                    },
                    "Address": {
                        "AddressLine": [
                            "{{verified_ship_to.address_1}}"{% if verified_ship_to.address_2 %}, "{{verified_ship_to.address_2}}"{% endif %}
                        ],
                        "City": "{{verified_ship_to.city}}",
                        "StateProvinceCode": "{{verified_ship_to.state}}",
                        "PostalCode": "{{verified_ship_to.postal_code}}",
                        "CountryCode": "{{verified_ship_to.country}}"
                    },
                    "Residential": ""
                },
                "ShipFrom": {
                    "Name": "{{ship_from.contact_name}}",
                    "AttentionName": "",
                    "Phone": {
                        "Number": "{{ship_from.phone}}"
                    },
                    "FaxNumber": "",
                    "Address": {
                        "AddressLine": [
                            "{{ship_from.address_1}}"{% if ship_from.address_2 %}, "{{ship_from.address_2}}"{% endif %}
                        ],
                        "City": "{{ship_from.city}}",
                        "StateProvinceCode": "{{ship_from.state}}",
                        "PostalCode": "{{ship_from.postal_code}}",
                        "CountryCode": "{{ship_from.country}}"
                    }
                },
                "PaymentInformation": {
                    "ShipmentCharge": {
                        "Type": "01",
                        "BillShipper": {
                            "AccountNumber": "{{carrier.account_number}}"
                        }
                    }
                },
                "Service": {
                    "Code": "{{shipping_service.code}}",
                    "Description": ""
                },
                "Package": [
                {% for package in order_packages %}
                    {
                        "Description": "",
                        "Packaging": {
                            "Code": "02",
                            "Description": ""
                        },
                        "Dimensions": {
                            "UnitOfMeasurement": {
                                "Code": "{{package.dimension_unit.upper()}}",
                                "Description": "{{package.dimension_unit.upper()}}"
                            },
                            "Length": "{{package.length}}",
                            "Width": "{{package.width}}",
                            "Height": "{{package.height}}"
                        },
                        "PackageWeight": {
                            "UnitOfMeasurement": {
                                "Code": "{% if package.weight_unit.upper() in ["LB", "LBS"] %}LBS{% else %}{{package.weight_unit.upper()}}{% endif %}",
                                "Description": ""
                            },
                            "Weight": "{{package.weight}}"
                        }
                    }{% if loop.index != order_packages | length %},{% endif %}
                {% endfor %}
                ]
            },
            "LabelSpecification": {
                "LabelImageFormat": {
                    "Code": "GIF",
                    "Description": "GIF"
                },
                "HTTPUserAgent": "Mozilla/4.5"
            },
            "ReferenceNumber": [
                {
                    "Code": "CUSTOMER_REFERENCE",
                    "Value": "{{shipping_ref_1}}"
                },
                {
                    "Code": "P_O_NUMBER",
                    "Value": "{{shipping_ref_2}}"
                },
                {
                    "Code": "INVOICE_NUMBER",
                    "Value": "{{shipping_ref_3}}"
                },
                {
                    "Code": "DEPARTMENT_NUMBER",
                    "Value": "{{shipping_ref_4}}"
                }
            ]
        }
    }"""
    ups_shipping_api.save()


def update_fedex_shipping_body(apps, schema_editor):
    fedex_service = Services.objects.filter(name="FEDEX").first()
    fedex_shipping_api = ServiceAPI.objects.filter(
        service=fedex_service.id, action=ServiceAPIAction.SHIPPING
    ).first()
    fedex_shipping_api.body = """{
        "labelResponseOptions": "URL_ONLY",
        "requestedShipment": {
            "shipper": {
                "address": {
                    "streetLines": [
                        "{{carrier.shipper.address}}"
                    ],
                    "city": "{{carrier.shipper.city}}",
                    "stateOrProvinceCode": "{{carrier.shipper.state}}",
                    "postalCode": "{{carrier.shipper.postal_code}}",
                    "countryCode": "{{carrier.shipper.country}}"
                },
                "contact": {
                    "personName": "{{carrier.shipper.name}}",
                    "emailAddress": "{{carrier.shipper.email}}",
                    "phoneNumber": "{{carrier.shipper.phone}}",
                    "companyName": "{{carrier.shipper.company}}"
                },
                "tins": [{"number": "", "tinType": "BUSINESS_UNION", "usage": ""}]
            },
            "recipients": [
                {
                    "contact": {
                        "personName": "{{verified_ship_to.contact_name}}",
                        "emailAddress": "",
                        "phoneNumber": "{{verified_ship_to.phone}}",
                        "companyName": "{{verified_ship_to.company}}"
                    },
                    "address": {
                        "streetLines": [
                            "{{verified_ship_to.address_1}}",
                            "{{verified_ship_to.address_2}}"
                        ],
                        "city": "{{verified_ship_to.city}}",
                        "stateOrProvinceCode": "{{verified_ship_to.state}}",
                        "postalCode": "{{verified_ship_to.postal_code}}",
                        "countryCode": "{{verified_ship_to.country}}"
                    }
                }
            ],
            "labelSpecification": {
                "imageType": "PNG",
                "labelStockType": "PAPER_4X6"
            },
            "shipDatestamp": "{{(datetime.date.today() + datetime.timedelta(days=5)).strftime("%Y-%m-%d")}}",
            "serviceType": "{{shipping_service.code}}",
            "packagingType": "YOUR_PACKAGING",
            "pickupType": "USE_SCHEDULED_PICKUP",
            "blockInsightVisibility": false,
            "edtRequestType": "NONE",
            "shippingChargesPayment": {
                "paymentType": "THIRD_PARTY",
                "payor": {
                    "responsibleParty": {
                        "address": {
                            "streetLines": ["10 FedEx Parkway", "Suite 302"],
                            "city": "Beverly Hills",
                            "stateOrProvinceCode": "CA",
                            "postalCode": "90210",
                            "countryCode": "US",
                            "residential": false
                        },
                        "accountNumber": {
                            "value": "{{carrier.account_number}}"
                        }
                    }
                }
            },
            "totalPackageCount": "{{order_packages | length}}",
            "requestedPackageLineItems": [
                {% for package in order_packages %}
                    {
                        "sequenceNumber": "{{loop.index}}",
                        "weight": {
                            "units": {% if package.weight_unit.upper() in ["LB", "LBS"] %}
                                "LB"
                            {% else %}
                                "{{package.weight_unit.upper()}}"
                            {% endif %},
                            "value": {{package.weight}}
                        },
                        "customerReferences": [
                            {
                                "customerReferenceType": "CUSTOMER_REFERENCE",
                                "value": "{{shipping_ref_1}}"
                            },
                            {
                                "customerReferenceType": "P_O_NUMBER",
                                "value": "{{shipping_ref_2}}"
                            },
                            {
                                "customerReferenceType": "INVOICE_NUMBER",
                                "value": "{{shipping_ref_3}}"
                            },
                            {
                                "customerReferenceType": "DEPARTMENT_NUMBER",
                                "value": "{{shipping_ref_4}}"
                            }
                        ],
                        "dimensions": {
                            "length": {{package.length}},
                            "width": {{package.width}},
                            "height": {{package.height}},
                            "units": "{{package.dimension_unit.upper()}}"
                        }
                    }{% if loop.index != order_packages | length %},{% endif %}
                {% endfor %}
            ]
        },
        "accountNumber": {"value": "{{carrier.account_number}}"},
        "shipAction": "CONFIRM",
        "processingOptionType": "SYNCHRONOUS_ONLY",
        "oneLabelAtATime": false
    }"""
    fedex_shipping_api.save()


class Migration(migrations.Migration):
    dependencies = [
        ("service_api", "0010_auto_20230812_0632"),
    ]

    operations = [
        migrations.RunPython(update_ups_shipping_body),
        migrations.RunPython(update_fedex_shipping_body),
    ]
