# Generated by Django 3.2.14 on 2023-08-30 08:18

from django.db import migrations
from selleraxis.service_api.models import ServiceAPI
from selleraxis.services.models import Services


def set_default_fedex_client(apps, schema_editor):
    fedex = Services.objects.filter(name="FEDEX").first()
    fedex_service = ServiceAPI.objects.filter(service=fedex, action="SHIPPING").first()
    fedex_service.response = """{
        "shipments": {
            "type": "list",
            "field": "{{output.transactionShipments.0.pieceResponses}}",
            "data": {
                "tracking_number": "{{trackingNumber}}",
                "package_document": "{{packageDocuments.0.url}}",
                "document_type": "url"
            }
        }
    }"""
    fedex_service.save()


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_services_shipment_tracking_url"),
        ("service_api", "0013_auto_20230830_0413"),
    ]

    operations = [migrations.RunPython(set_default_fedex_client)]
