# Generated by Django 3.2.14 on 2023-10-06 09:11

from django.db import migrations
from selleraxis.service_api.models import ServiceAPI
from selleraxis.services.models import Services


def set_up_body_ups_and_fedex_client(apps, schema_editor):
    ups = Services.objects.filter(name="UPS").first()
    ServiceAPI.objects.filter(service=ups, action="SHIPPING").update(
        body="""{
        "ShipmentRequest": {
            "Request": {
                "SubVersion": "1801",
                "RequestOption": "nonvalidate",
                "TransactionReference": {
                    "CustomerContext": ""
                }
            },
            "Shipment": {
                "Description": "Infibrite Shipment",
                "Shipper": {
                    "Name": "{{carrier.shipper.name}}",
                    "AttentionName": "{{carrier.shipper.attention_name}}",
                    "TaxIdentificationNumber": "{{carrier.shipper.tax_identification_number}}",
                    "Phone": {
                        "Number": "{{carrier.shipper.phone}}",
                        "Extension": ""
                    },
                    "ShipperNumber": "{{carrier.shipper.shipper_number}}",
                    "FaxNumber": "{{carrier.shipper.fax_number}}",
                    "Address": {
                        "AddressLine": "{{carrier.shipper.address}}",
                        "City": "{{carrier.shipper.city}}",
                        "StateProvinceCode": "{{carrier.shipper.state}}",
                        "PostalCode": "{{carrier.shipper.postal_code}}",
                        "CountryCode": "{{carrier.shipper.country}}"
                    }
                },
                "ShipTo": {
                    "Name": "{{verified_ship_to.contact_name}}",
                    "AttentionName": "{{verified_ship_to.contact_name}}",
                    "Phone": {
                        "Number": "{{verified_ship_to.phone}}"
                    },
                    "Address": {
                        "AddressLine": [
                            "{{verified_ship_to.address_1}}"{% if verified_ship_to.address_2 %}, "{{verified_ship_to.address_2}}"{% endif %}
                        ],
                        "City": "{{verified_ship_to.city}}",
                        "StateProvinceCode": "{{verified_ship_to.state}}",
                        "PostalCode": "{{verified_ship_to.postal_code}}",
                        "CountryCode": "{{verified_ship_to.country}}"
                    },
                    "Residential": ""
                },
                "ShipFrom": {
                    "Name": "{{ship_from.contact_name}}",
                    "AttentionName": "",
                    "Phone": {
                        "Number": "{{ship_from.phone}}"
                    },
                    "FaxNumber": "",
                    "Address": {
                        "AddressLine": [
                            "{{ship_from.address_1}}"{% if ship_from.address_2 %}, "{{ship_from.address_2}}"{% endif %}
                        ],
                        "City": "{{ship_from.city}}",
                        "StateProvinceCode": "{{ship_from.state}}",
                        "PostalCode": "{{ship_from.postal_code}}",
                        "CountryCode": "{{ship_from.country}}"
                    }
                },
                "PaymentInformation": {
                    "ShipmentCharge": {
                        "Type": "01",
                        "BillShipper": {
                            "AccountNumber": "{{carrier.account_number}}"
                        }
                    }
                },
                "Service": {
                    "Code": "{{shipping_service.code}}",
                    "Description": ""
                },
                "Package": [
                {% for package in order_packages %}
                    {
                        "Description": "",
                        "Packaging": {
                            "Code": "02",
                            "Description": ""
                        },
                        "Dimensions": {
                            "UnitOfMeasurement": {
                                "Code": "{{package.dimension_unit.upper()}}",
                                "Description": "{{package.dimension_unit.upper()}}"
                            },
                            "Length": "{{package.length}}",
                            "Width": "{{package.width}}",
                            "Height": "{{package.height}}"
                        },
                        "PackageWeight": {
                            "UnitOfMeasurement": {
                                "Code": "{% if package.weight_unit.upper() in ["LB", "LBS"] %}LBS{% else %}{{package.weight_unit.upper()}}{% endif %}",
                                "Description": ""
                            },
                            "Weight": "{{package.weight}}"
                        }
                    }{% if loop.index != order_packages | length %},{% endif %}
                {% endfor %}
                ]
            },
            "LabelSpecification": {
                "LabelImageFormat": {
                    "Code": "GIF",
                    "Description": "GIF"
                },
                "HTTPUserAgent": "Mozilla/4.5"
            },
            "ReferenceNumber": [
              {% if shipping_ref_1_code %}
                {
                    "Code": "{{shipping_ref_1_code}}",
                    "Value": "{{shipping_ref_1}}"
                },
              {% endif %}
              {% if shipping_ref_2_code %}
                {
                    "Code": "{{shipping_ref_2_code}}",
                    "Value": "{{shipping_ref_2}}"
                },
              {% endif %}
              {% if shipping_ref_3_code %}
                {
                    "Code": "{{shipping_ref_3_code}}",
                    "Value": "{{shipping_ref_3}}"
                },
              {% endif %}
              {% if shipping_ref_4_code %}
                {
                    "Code": "{{shipping_ref_4_code}}",
                    "Value": "{{shipping_ref_4}}"
                }
              {% endif %}
            ]
        }
    }"""
    )
    fedex = Services.objects.filter(name="FEDEX").first()
    ServiceAPI.objects.filter(service=fedex, action="SHIPPING").update(
        body="""{
        "labelResponseOptions": "URL_ONLY",
        "requestedShipment": {
            "shipper": {
                "address": {
                    "streetLines": [
                        "{{ship_from.address_1}}","{{ship_from.address_2}}"
                    ],
                    "city": "{{ship_from.city}}",
                    "stateOrProvinceCode": "{{ship_from.state}}",
                    "postalCode": "{{ship_from.postal_code}}",
                    "countryCode": "{{ship_from.country}}"
                },
                "contact": {
                    "personName": "{{ship_from.contact_name}}",
                    "emailAddress": "{{ship_from.email}}",
                    "phoneNumber": "{{ship_from.phone}}",
                    "companyName": "{{ship_from.company}}"
                },
                "tins": [{"number": "", "tinType": "BUSINESS_UNION", "usage": ""}]
            },
            "recipients": [
                {
                    "contact": {
                        "personName": "{{verified_ship_to.contact_name}}",
                        "emailAddress": "",
                        "phoneNumber": "{{verified_ship_to.phone}}",
                        "companyName": "{{verified_ship_to.company}}"
                    },
                    "address": {
                        "streetLines": [
                            "{{verified_ship_to.address_1}}",
                            "{{verified_ship_to.address_2}}"
                        ],
                        "city": "{{verified_ship_to.city}}",
                        "stateOrProvinceCode": "{{verified_ship_to.state}}",
                        "postalCode": "{{verified_ship_to.postal_code}}",
                        "countryCode": "{{verified_ship_to.country}}",
                        "residential": "{{shipping_service.is_require_residential}}"
                    }
                }
            ],
            "labelSpecification": {
                "imageType": "PNG",
                "labelStockType": "PAPER_4X6"
            },
            {% if not ship_date %}
              {% set formatted_ship_date =datetime.date.today().strftime("%Y-%m-%d") %}
            {% else %}
              {% set formatted_ship_date = ship_date[:10] %}
            {% endif %}
            "shipDatestamp": "{{ formatted_ship_date }}",
            "serviceType": "{{shipping_service.code}}",
            "packagingType": "YOUR_PACKAGING",
            "pickupType": "USE_SCHEDULED_PICKUP",
            "blockInsightVisibility": false,
            "edtRequestType": "NONE",
            "shippingChargesPayment": {
                "paymentType": "THIRD_PARTY",
                "payor": {
                    "responsibleParty": {
                        "address": {
                            "streetLines": ["", ""],
                            "city": "",
                            "stateOrProvinceCode": "",
                            "postalCode": "",
                            "countryCode": "",
                            "residential": false
                        },
                        "accountNumber": {
                            "value": "{{carrier.account_number}}"
                        }
                    }
                }
            },
            "totalPackageCount": "{{order_packages | length}}",
            "requestedPackageLineItems": [
                {% for package in order_packages %}
                    {
                        "sequenceNumber": "{{loop.index}}",
                        "weight": {
                            "units": {% if package.weight_unit.upper() in ["LB", "LBS"] %}
                                "LB"
                            {% else %}
                                "{{package.weight_unit.upper()}}"
                            {% endif %},
                            "value": {{package.weight}}
                        },
                        "customerReferences": [
                          {% if shipping_ref_1_code %}
                            {
                                "customerReferenceType": "{{shipping_ref_1_code}}",
                                "value": "{{shipping_ref_1}}"
                            },
                          {% endif %}
                          {% if shipping_ref_2_code %}
                            {
                                "customerReferenceType": "{{shipping_ref_2_code}}",
                                "value": "{{shipping_ref_2}}"
                            },
                          {% endif %}
                          {% if shipping_ref_3_code %}
                            {
                                "customerReferenceType": "{{shipping_ref_3_code}}",
                                "value": "{{shipping_ref_3}}"
                            },
                          {% endif %}
                          {% if shipping_ref_4_code %}
                            {
                                "customerReferenceType": "{{shipping_ref_4_code}}",
                                "value": "{{shipping_ref_4}}"
                            }
                          {% endif %}
                        ],
                        "dimensions": {
                            "length": {{package.length}},
                            "width": {{package.width}},
                            "height": {{package.height}},
                            "units": "{{package.dimension_unit.upper()}}"
                        }
                    }{% if loop.index != order_packages | length %},{% endif %}
                {% endfor %}
            ]
        },
        "accountNumber": {"value": "{{carrier.account_number}}"},
        "shipAction": "CONFIRM",
        "processingOptionType": "SYNCHRONOUS_ONLY",
        "oneLabelAtATime": false
    }"""
    )


class Migration(migrations.Migration):
    dependencies = [
        ("service_api", "0019_auto_20230929_0621"),
    ]

    operations = [migrations.RunPython(set_up_body_ups_and_fedex_client)]
