# Generated by Django 3.2.14 on 2023-07-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_person_places", "0001_initial"),
        ("retailer_purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="verified_ship_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verified_ship_to_orders",
                to="retailer_person_places.retailerpersonplace",
            ),
        ),
    ]
