# Generated by Django 3.2.14 on 2023-07-26 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_purchase_orders", "0002_retailerpurchaseorder_verified_ship_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="declared_value",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="ship_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, null=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Delivered", "Delivered"),
                    ("Confirmed", "Confirmed"),
                    ("Acknowledged", "Acknowledged"),
                    ("Shipping", "Shipping"),
                    ("Shipped", "Shipped"),
                    ("Cancelled", "Cancelled"),
                    ("Cancelling", "Cancelling"),
                    ("Invoiced", "Invoiced"),
                    ("Closed", "Closed"),
                ],
                default="Received",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
