# Generated by Django 3.2.14 on 2023-07-27 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_purchase_orders", "0003_auto_20230726_0825"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailerpurchaseorder",
            name="weight",
        ),
    ]
