# Generated by Django 3.2.14 on 2023-08-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_purchase_orders", "0005_auto_20230727_0822"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerpurchaseorder",
            name="ship_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="retailerpurchaseorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
