# Generated by Django 3.2.14 on 2023-08-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_verified_address", "0001_initial"),
        ("retailer_purchase_orders", "0006_auto_20230802_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerpurchaseorder",
            name="verified_ship_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verified_ship_to_orders",
                to="order_verified_address.orderverifiedaddress",
            ),
        ),
    ]
