# Generated by Django 3.2.14 on 2023-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "retailer_purchase_orders",
            "0007_alter_retailerpurchaseorder_verified_ship_to",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Opened", "Opened"),
                    ("Delivered", "Delivered"),
                    ("Confirmed", "Confirmed"),
                    ("Acknowledged", "Acknowledged"),
                    ("Shipping", "Shipping"),
                    ("Shipped", "Shipped"),
                    ("Cancelled", "Cancelled"),
                    ("Cancelling", "Cancelling"),
                    ("Invoiced", "Invoiced"),
                    ("Closed", "Closed"),
                ],
                default="Opened",
                max_length=255,
            ),
        ),
    ]
