# Generated by Django 3.2.14 on 2023-08-10 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_verified_address", "0001_initial"),
        ("retailer_purchase_orders", "0008_alter_retailerpurchaseorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="ship_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ship_from_orders",
                to="order_verified_address.orderverifiedaddress",
            ),
        ),
    ]
