# Generated by Django 4.2.3 on 2023-08-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailer_purchase_orders", "0009_retailerpurchaseorder_ship_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="is_divide",
            field=models.BooleanField(default=False),
        ),
    ]
