# Generated by Django 3.2.14 on 2023-08-15 02:35

from django.db import migrations
from selleraxis.retailer_purchase_orders.models import RetailerPurchaseOrder


def migrate_status_purchase_order(apps, schema_editor):
    RetailerPurchaseOrder.objects.filter(status="Received").update(status="Opened")


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_purchase_orders", "0009_retailerpurchaseorder_ship_from"),
    ]

    operations = [
        migrations.RunPython(migrate_status_purchase_order),
    ]
