# Generated by Django 4.2.3 on 2023-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailer_purchase_orders", "0010_auto_20230815_0235"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="is_divide",
            field=models.BooleanField(default=False),
        ),
    ]
