# Generated by Django 3.2.14 on 2023-08-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gs1", "0001_initial"),
        ("retailer_purchase_orders", "0012_alter_retailerpurchaseorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="gs1",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="gs1.gs1"
            ),
        ),
    ]
