# Generated by Django 3.2.14 on 2023-08-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_purchase_orders", "0013_retailerpurchaseorder_gs1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Opened", "Opened"),
                    ("Acknowledged", "Acknowledged"),
                    ("Shipped", "Shipped"),
                    ("Shipment Confirmed", "Shipment Confirmed"),
                    ("Invoiced", "Invoiced"),
                    ("Invoice Confirmed", "Invoice Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Opened",
                max_length=255,
            ),
        ),
    ]
