# Generated by Django 3.2.14 on 2023-10-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_order_batchs", "0002_retailerorderbatch_file_name"),
        (
            "retailer_purchase_orders",
            "0018_alter_retailerpurchaseorder_shipping_service",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerpurchaseorder",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_batch",
                to="retailer_order_batchs.retailerorderbatch",
            ),
        ),
    ]
