# Generated by Django 3.2.14 on 2023-10-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_purchase_orders", "0019_alter_retailerpurchaseorder_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="estimated_delivery_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="estimated_ship_date",
            field=models.DateTimeField(null=True),
        ),
    ]
