# Generated by Django 3.2.14 on 2023-11-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailer_purchase_orders", "0021_alter_retailerpurchaseorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Opened", "Opened"),
                    ("Acknowledged", "Acknowledged"),
                    ("Shipped", "Shipped"),
                    ("Partly Shipped", "Partly Shipped"),
                    ("Partly Shipped Confirmed", "Partly Shipped Confirmed"),
                    ("Shipment Confirmed", "Shipment Confirmed"),
                    ("Invoiced", "Invoiced"),
                    ("Invoice Confirmed", "Invoice Confirmed"),
                    ("Cancelled", "Cancelled"),
                    ("Bypassed Acknowledge", "Bypassed Acknowledge"),
                    ("Backorder", "Backorder"),
                ],
                default="Opened",
                max_length=255,
            ),
        ),
    ]
