# Generated by Django 3.2.14 on 2023-11-07 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_warehouses", "0004_auto_20230814_0814"),
        ("retailer_purchase_orders", "0022_alter_retailerpurchaseorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_warehouse",
                to="retailer_warehouses.retailerwarehouse",
            ),
        ),
    ]
