# Generated by Django 3.2.14 on 2023-11-24 03:23

from django.db import migrations, models


def recheck_order_status(apps, schema_editor):
    # get all order
    RetailerPurchaseOrder = apps.get_model(
        "retailer_purchase_orders", "RetailerPurchaseOrder"
    )
    list_order = RetailerPurchaseOrder.objects.all()

    # get all order package
    OrderPackage = apps.get_model("order_package", "OrderPackage")
    list_order_package = OrderPackage.objects.all()

    # get all shipment
    Shipment = apps.get_model("shipments", "Shipment")
    list_shipment = Shipment.objects.all()
    list_package_id_shipped = []
    for shipment_item in list_shipment:
        if shipment_item.package is not None:
            list_package_id_shipped.append(shipment_item.package.id)

    for order in list_order:
        # get list package shipped of order
        list_package_shipped_for_order = list_order_package.filter(
            order__id=order.id, id__in=list_package_id_shipped
        )
        if len(list_package_shipped_for_order) > 0:
            order.ship_times = 1
        else:
            order.ship_times = 0
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("retailer_purchase_orders", "0025_update_status_for_order_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerpurchaseorder",
            name="ship_times",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(recheck_order_status),
    ]
