# Generated by Django 3.2.14 on 2023-08-14 11:42

from django.db import migrations, models
from selleraxis.retailer_suggestion.models import RetailerSuggestion

RETAILER_NAME = "CommerceHub The Home Depot Merchant SKU"
RETAILER_TYPE = "CommerceHub"
MERCHANT_SKU_PREFIXES = ["100", "20", "3"]
MERCHANT_ID = "thehomedepot"


def forwards(app, app_schema):
    RetailerSuggestion.objects.create(
        name=RETAILER_NAME,
        merchant_id=MERCHANT_ID,
        type=RETAILER_TYPE,
        merchant_sku_prefix=MERCHANT_SKU_PREFIXES,
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RetailerSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("merchant_sku_prefix", models.JSONField(default=list)),
                ("merchant_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(forwards),
    ]
