# Generated by Django 3.2.14 on 2023-08-15 07:54

from django.db import migrations, models
from selleraxis.retailer_suggestion.models import RetailerSuggestion

RETAILER_NAME = "CommerceHub The Home Depot Merchant SKU"
RETAILER_TYPE = "CommerceHub"
MERCHANT_SKU_PREFIXES = ["100", "20", "3"]
MERCHANT_ID = "thehomedepot"
MIN_LENGTH = MAX_LENGTH = 9


def forwards(app, app_schema):
    RetailerSuggestion.objects.create(
        name=RETAILER_NAME,
        merchant_id=MERCHANT_ID,
        type=RETAILER_TYPE,
        merchant_sku_prefix=MERCHANT_SKU_PREFIXES,
        merchant_sku_min_length=MIN_LENGTH,
        merchant_sku_max_length=MAX_LENGTH,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("retailer_suggestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailersuggestion",
            name="merchant_sku_max_length",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="retailersuggestion",
            name="merchant_sku_min_length",
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(forwards),
    ]
